// motion-engine unit tests — proves the engine runs headless (no three.js /
// browser), is deterministic, and produces a sane plain-data Pose.
//   node test.mjs    (or: npm test)
import {
  MotionEngine, Gesture, Spring, MANAGED, REST, GESTURE_DUR,
  Reach, Place, PLACE_STYLES, solveTwoBone, fkHand, qFromEulerXYZ, qToEulerXYZ,
  Grip, Pick, gripPose, FINGER_BONES, projectOut, makeArmConstraint, swingEnv,
} from './index.js';

const D = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);

let pass = 0, fail = 0;
const ok = (cond, msg) => { if (cond) { pass++; } else { fail++; console.error('  ✗ ' + msg); } };
const finite = (e) => e.every((v) => Number.isFinite(v));

// drive an engine for `steps` frames at 60fps, optionally with a queued action.
function run(makeAction) {
  const eng = new MotionEngine();
  if (makeAction) eng.play(makeAction());
  const dt = 1 / 60;
  const trace = [];
  for (let i = 0; i < 300; i++) {
    trace.push(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }));
  }
  return trace;
}

// 1) deterministic: identical inputs → byte-identical pose stream (no Math.random)
{
  const a = run(() => new Gesture('tsumogiri'));
  const b = run(() => new Gesture('tsumogiri'));
  let same = true;
  for (let i = 0; i < a.length; i++) {
    for (const bone of MANAGED) {
      const x = a[i][bone], y = b[i][bone];
      if (x[0] !== y[0] || x[1] !== y[1] || x[2] !== y[2]) same = false;
    }
  }
  ok(same, 'engine is deterministic across runs');
}

// 2) output is well-formed: every MANAGED bone present, all finite, every frame
{
  const trace = run();
  let wellFormed = true;
  for (const pose of trace) {
    for (const bone of MANAGED) {
      if (!pose[bone] || pose[bone].length !== 3 || !finite(pose[bone])) wellFormed = false;
    }
  }
  ok(wellFormed, 'pose has every MANAGED bone as a finite [x,y,z]');
}

// 3) idle is ALIVE (head actually drifts) but bounded (not flailing)
{
  const trace = run();
  const headY = trace.map((p) => p.head[1]);
  const moved = Math.max(...headY) - Math.min(...headY);
  ok(moved > 0.01, 'idle head drifts (alive, not frozen)');
  ok(Math.max(...headY.map(Math.abs)) < 0.3, 'idle head stays bounded');
}

// 4) a one-shot gesture peaks then SETTLES back toward rest
{
  const trace = run(() => new Gesture('fistPump'));   // dur 1.0s → done by frame 60
  const rz = trace.map((p) => p.rightUpperArm[2]);    // rest z = -1.2, fist raises it
  const peak = Math.max(...rz);
  const settled = rz[rz.length - 1];
  ok(peak > -0.2, 'fistPump raises the right arm well above rest');
  ok(Math.abs(settled - REST.rightUpperArm[2]) < 0.08, 'arm settles back to rest after the gesture');
}

// 5) spring is stable under a huge dt spike (tab refocus) — no NaN/blowup
{
  const s = new Spring(2.4, 0.9, 0, 0);
  s.update(100, 1);            // 100-second frame
  const v = s.update(1 / 60, 1);
  ok(Number.isFinite(v), 'spring survives a huge dt without NaN');
}

// 6) emotion micro-pose drives the head, scaled by weight
{
  const eng = new MotionEngine();
  const dt = 1 / 60;
  let last;
  for (let i = 0; i < 200; i++) last = eng.update(dt, { t: i * dt, phase: 0, pose: { headPitch: 0.2 }, poseW: 1 });
  ok(last.head[0] > 0.1, 'emotion headPitch is reflected in the head pose');
}

// --- Phase 2: inverse kinematics -------------------------------------------
// a self-consistent right-arm rig (values are arbitrary but FK-consistent;
// the test validates the MATH + Euler/quat conventions, not a specific VRM).
const ARM = { pU: [0.18, 1.3, 0], pL: [0, -0.26, 0], pH: [0, -0.24, 0], restU: [0, 0, -1.2], restL: [0, 0.3, 0] };
const RU = qFromEulerXYZ(ARM.restU), RL = qFromEulerXYZ(ARM.restL);
const REST_HAND = fkHand(ARM.pU, ARM.pL, ARM.pH, RU, RL);

// 7) Euler↔quat round-trip matches three.js 'XYZ' order (so bone.rotation.set works)
{
  const e = [0.3, -0.7, 1.1];
  const b = qToEulerXYZ(qFromEulerXYZ(e));
  ok(Math.max(Math.abs(b[0] - e[0]), Math.abs(b[1] - e[1]), Math.abs(b[2] - e[2])) < 1e-9, 'eulerXYZ↔quat round-trips (three.js convention)');
}

// 8) two-bone IK reaches any reachable hand position. Targets are generated by
//    FK of a perturbed pose so they are guaranteed inside the arm's reach shell;
//    the solver must land the hand back on each (IK∘FK = identity on position).
{
  let maxErr = 0;
  for (const dp of [[0.2, 0.1, -0.3], [-0.3, 0.4, 0.2], [0.1, -0.2, 0.5], [0.4, 0.1, -0.1], [-0.25, -0.3, 0.3]]) {
    const uq = qFromEulerXYZ([ARM.restU[0] + dp[0], ARM.restU[1] + dp[1], ARM.restU[2] + dp[2]]);
    const lq = qFromEulerXYZ([ARM.restL[0] + dp[2] * 0.5, ARM.restL[1] + dp[0] * 0.5, ARM.restL[2]]);
    const target = fkHand(ARM.pU, ARM.pL, ARM.pH, uq, lq);   // guaranteed reachable
    const { upperQ, lowerQ } = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, target);
    const hand = fkHand(ARM.pU, ARM.pL, ARM.pH, upperQ, lowerQ);
    maxErr = Math.max(maxErr, Math.hypot(hand[0] - target[0], hand[1] - target[1], hand[2] - target[2]));
  }
  ok(maxErr < 1e-3, 'two-bone IK reaches reachable hand positions (maxErr=' + maxErr.toFixed(6) + ')');
}

// 8b) POLE VECTOR: as the target sweeps, the elbow tracks CONSISTENTLY on the
//     pole side and moves smoothly (no shortest-arc flip). This is the anti-
//     "unnatural elbow" fix — the elbow must not jump plane between frames.
{
  const pole = [0, -1, -0.3];                          // push the elbow down-and-back
  const elbowAt = (t) => {
    const { upperQ } = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, t, { pole });
    return fkElbow(ARM.pU, ARM.pL, upperQ);
  };
  let sameSide = true, maxJump = 0, prev = null;
  for (let i = 0; i <= 20; i++) {
    const x = -0.4 + (0.8 * i) / 20;                   // sweep the hand left→right
    const t = [ARM.pU[0] + x, ARM.pU[1] - 0.35, ARM.pU[2] + 0.35];
    const elbow = elbowAt(t);
    // elbow offset from the shoulder→target line must lean toward the pole (y<0)
    const dir = vn(sub(t, ARM.pU));
    const off = sub(sub(elbow, ARM.pU), scl(dir, dot(sub(elbow, ARM.pU), dir)));
    if (dot(off, pole) <= 0) sameSide = false;
    if (prev) maxJump = Math.max(maxJump, D(elbow, prev));
    prev = elbow;
  }
  ok(sameSide, 'elbow stays on the pole side across a target sweep (no flip)');
  ok(maxJump < 0.08, 'elbow moves smoothly across the sweep (maxJump=' + maxJump.toFixed(4) + ')');
}

// 8c) flipping the pole flips which side the elbow bends toward
{
  const t = [ARM.pU[0] + 0.15, ARM.pU[1] - 0.3, ARM.pU[2] + 0.35];
  const down = fkElbow(ARM.pU, ARM.pL, solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, t, { pole: [0, -1, 0] }).upperQ);
  const up = fkElbow(ARM.pU, ARM.pL, solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, t, { pole: [0, 1, 0] }).upperQ);
  ok(down[1] < up[1] - 0.05, 'pole direction controls the elbow side (down pole → lower elbow)');
}

// 9) unreachable target clamps to near max extension (finite, no NaN)
{
  const far = [ARM.pU[0] + 3, ARM.pU[1], ARM.pU[2]];
  const { upperQ, lowerQ } = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, far);
  const hand = fkHand(ARM.pU, ARM.pL, ARM.pH, upperQ, lowerQ);
  const reach = Math.hypot(hand[0] - ARM.pU[0], hand[1] - ARM.pU[1], hand[2] - ARM.pU[2]);
  const L = vl(ARM.pL) + vl(ARM.pH);
  ok([...upperQ, ...lowerQ, ...hand].every(Number.isFinite) && reach > L * 0.9 && reach <= L, 'unreachable target clamps to ~max extension');
}

// 10) Reach action drives the hand to the target, then releases back to rest
{
  const target = [REST_HAND[0] + 0.1, REST_HAND[1] + 0.08, REST_HAND[2] + 0.05];
  const eng = new MotionEngine();
  eng.play(new Reach('right', ARM, target, 1.2, { hold: 0.4 }));
  const dt = 1 / 60; let peakErr = 1e9; let last;
  for (let i = 0; i < 72; i++) {                       // 1.2s reach
    last = eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 });
    const hand = fkHand(ARM.pU, ARM.pL, ARM.pH, qFromEulerXYZ(last.rightUpperArm), qFromEulerXYZ(last.rightLowerArm));
    peakErr = Math.min(peakErr, Math.hypot(hand[0] - target[0], hand[1] - target[1], hand[2] - target[2]));
  }
  ok(peakErr < 0.02, 'Reach brings the hand to the target at full extension (peakErr=' + peakErr.toFixed(4) + ')');
  for (let i = 0; i < 120; i++) last = eng.update(dt, { t: (72 + i) * dt, phase: 0, pose: {}, poseW: 0 });
  ok(Math.abs(last.rightUpperArm[2] - REST.rightUpperArm[2]) < 0.1, 'arm returns to rest after the reach');
}

// --- v0.2: Place action ----------------------------------------------------
const GEO = Object.assign({}, ARM, { restW: [0, 0, 0] });
const handAt = (pose) => fkHand(ARM.pU, ARM.pL, ARM.pH, qFromEulerXYZ(pose.rightUpperArm), qFromEulerXYZ(pose.rightLowerArm));
function runPlace(target, opts, secs = 2.2) {
  const eng = new MotionEngine();
  eng.play(new Place('right', GEO, target, opts));
  const dt = 1 / 60; const trace = [];
  for (let i = 0; i < Math.ceil(secs * 60); i++) trace.push(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }));
  return trace;
}

// 11) Place(gentle) lands the hand on the target (through the spring chain)
{
  const target = [REST_HAND[0] + 0.12, REST_HAND[1] - 0.05, REST_HAND[2] + 0.08];
  let peak = 1e9;
  for (const pose of runPlace(target, { style: 'gentle' })) peak = Math.min(peak, D(handAt(pose), target));
  ok(peak < 0.05, 'Place(gentle) lands the hand on the target (peakErr=' + peak.toFixed(4) + ')');
}

// 12) the hand ARCS up (lift over a downward target — not a straight drop)
{
  const target = [REST_HAND[0] + 0.12, REST_HAND[1] - 0.06, REST_HAND[2] + 0.08];
  let maxY = -1e9;
  for (const pose of runPlace(target, { style: 'gentle', arc: 0.1 }, 1.0)) maxY = Math.max(maxY, handAt(pose)[1]);
  ok(maxY > REST_HAND[1] + 0.01, 'hand lifts above the start (gravity lift arc, not a straight drop)');
}

// 13) Place drives the shoulder (roll/swing) and the wrist (aim/snap/twist)
{
  let sh = 0, wr = 0;
  for (const pose of runPlace([REST_HAND[0] + 0.12, REST_HAND[1], REST_HAND[2] + 0.08], { style: 'jam' }, 1.0)) {
    sh = Math.max(sh, Math.abs(pose.rightShoulder[0]) + Math.abs(pose.rightShoulder[1]));
    wr = Math.max(wr, Math.abs(pose.rightHand[0]) + Math.abs(pose.rightHand[1]) + Math.abs(pose.rightHand[2]));
  }
  ok(sh > 0.02, 'Place rolls the shoulder (clavicle lead)');
  ok(wr > 0.02, 'Place drives the wrist independently (aim/snap/twist)');
}

// 14) snap gives a sharper wrist flick than gentle (peak angular speed)
{
  const peakWristSpeed = (style) => {
    let prev = null, mx = 0; const dt = 1 / 60;
    for (const pose of runPlace([REST_HAND[0] + 0.1, REST_HAND[1], REST_HAND[2] + 0.06], { style })) {
      const v = pose.rightHand;
      if (prev) mx = Math.max(mx, (Math.abs(v[0] - prev[0]) + Math.abs(v[1] - prev[1]) + Math.abs(v[2] - prev[2])) / dt);
      prev = v;
    }
    return mx;
  };
  ok(peakWristSpeed('snap') > peakWristSpeed('gentle') * 1.5, 'snap = a faster wrist flick than gentle');
}

// 15) linger keeps the hand on the tile longer than snap (なかなか離さない)
{
  const target = [REST_HAND[0] + 0.12, REST_HAND[1] - 0.04, REST_HAND[2] + 0.08];
  const framesOn = (style) => runPlace(target, { style }).filter((pose) => D(handAt(pose), target) < 0.04).length;
  ok(framesOn('linger') > framesOn('snap'), 'linger dwells on the tile longer than snap');
}

// 16) Place is deterministic
{
  const run = () => runPlace([REST_HAND[0] + 0.1, REST_HAND[1], REST_HAND[2] + 0.06], { style: 'jam' }, 1.4).map((p) => p.rightHand);
  const a = run(), b = run(); let same = true;
  for (let i = 0; i < a.length; i++) for (let k = 0; k < 3; k++) if (a[i][k] !== b[i][k]) same = false;
  ok(same, 'Place is deterministic');
}

// --- v0.3: richer one-shot gestures ----------------------------------------

// 17) every new gesture is registered (has a duration) and is a known function
{
  const v03 = ['recoil', 'crossArms', 'nod', 'shrug', 'lean', 'smirkTilt', 'sigh', 'exhale'];
  let allDur = true, allFn = true;
  for (const name of v03) {
    if (!(GESTURE_DUR[name] > 0)) allDur = false;
    if (new Gesture(name).done) allFn = false;   // ctor sets done=true when the fn is missing
  }
  ok(allDur, 'all v0.3 gestures have a duration');
  ok(allFn, 'all v0.3 gestures resolve to a real function (not no-op)');
}

// 18) each new gesture actually MOVES its signature bone, then settles back
{
  // bone whose displacement from rest is the gesture's "tell"
  const sig = { recoil: 'chest', crossArms: 'rightLowerArm', nod: 'head', shrug: 'rightShoulder', lean: 'spine', smirkTilt: 'head' };
  const axis = { recoil: 0, crossArms: 1, nod: 0, shrug: 2, lean: 0, smirkTilt: 2 };
  let allMoved = true, allSettled = true;
  for (const name of Object.keys(sig)) {
    const bone = sig[name], ax = axis[name];
    const rest = (REST[bone] || [0, 0, 0])[ax];
    const trace = run(() => new Gesture(name));
    let peak = 0; for (const p of trace) peak = Math.max(peak, Math.abs(p[bone][ax] - rest));
    const settled = Math.abs(trace[trace.length - 1][bone][ax] - rest);
    if (peak < 0.12) { allMoved = false; console.error('    ' + name + ' barely moved (peak=' + peak.toFixed(3) + ')'); }
    if (settled > 0.06) { allSettled = false; console.error('    ' + name + ' did not settle (residual=' + settled.toFixed(3) + ')'); }
  }
  ok(allMoved, 'every v0.3 gesture visibly moves its signature bone');
  ok(allSettled, 'every v0.3 gesture settles back to rest when done');
}

// 19) crossArms folds BOTH forearms inward (left −Y, right +Y past rest)
{
  const trace = run(() => new Gesture('crossArms'));
  let lMin = 9, rMax = -9;
  for (const p of trace) { lMin = Math.min(lMin, p.leftLowerArm[1]); rMax = Math.max(rMax, p.rightLowerArm[1]); }
  ok(lMin < REST.leftLowerArm[1] - 0.3 && rMax > REST.rightLowerArm[1] + 0.3, 'crossArms bends both forearms across the chest');
}

// 20) the new gestures are deterministic (no Math.random)
{
  const a = run(() => new Gesture('recoil')), b = run(() => new Gesture('recoil'));
  let same = true;
  for (let i = 0; i < a.length; i++) for (const bone of MANAGED) for (let k = 0; k < 3; k++) if (a[i][bone][k] !== b[i][bone][k]) same = false;
  ok(same, 'v0.3 gestures are deterministic');
}

// 21) ctx.gain (v0.4) scales gesture amplitude — big vs reserved reactions
{
  const peakChest = (gain) => {
    const eng = new MotionEngine();
    eng.play(new Gesture('recoil'));
    const dt = 1 / 60; let mx = 0;
    for (let i = 0; i < 90; i++) {
      const ctx = { t: i * dt, phase: 0, pose: {}, poseW: 0 };
      if (gain != null) ctx.gain = gain;
      const p = eng.update(dt, ctx);
      mx = Math.max(mx, Math.abs(p.chest[0]));
    }
    return mx;
  };
  const lo = peakChest(0.5), mid = peakChest(1), hi = peakChest(2);
  ok(hi > mid * 1.4 && mid > lo * 1.4, `gain scales gesture amplitude (0.5→${lo.toFixed(3)} 1→${mid.toFixed(3)} 2→${hi.toFixed(3)})`);
  ok(Math.abs(peakChest(null) - mid) < 1e-9, 'no gain == gain 1 (back-compatible default)');
  ok(Math.abs(peakChest(99) - peakChest(2.5)) < 1e-9, 'gain is clamped (≤2.5)');
}

// --- v0.5: fingers — grip + Pick (grab a tile, carry it out, place it) -------

// 22) finger bones joined the managed rig and the engine emits them, finite
{
  const want = ['leftIndexProximal', 'rightThumbDistal', 'leftLittleIntermediate', 'rightMiddleProximal'];
  ok(want.every((b) => MANAGED.includes(b)), 'finger bones are in MANAGED');
  const last = run()[120];
  ok(want.every((b) => last[b] && finite(last[b])), 'engine emits finite finger poses');
}

// 23) gripPose: a closed grip curls the fingers; open ≈ straight; sign flips per hand
{
  const open = gripPose('right', 0);
  const closed = gripPose('right', 1);
  const openCurl = Math.abs(open.rightIndexProximal[2]);
  const closedCurl = Math.abs(closed.rightIndexProximal[2]);
  ok(openCurl < 1e-9, 'gripPose(0) leaves the finger straight');
  ok(closedCurl > 0.5, 'gripPose(1) curls the finger toward the palm');
  ok(Math.sign(gripPose('left', 1).leftIndexProximal[2]) === -Math.sign(closed.rightIndexProximal[2]),
    'left/right fingers curl with opposite Z sign');
  ok(Math.sign(gripPose('right', 1, { flexSign: -1 }).rightIndexProximal[2]) === -Math.sign(closedCurl ? closed.rightIndexProximal[2] : 1),
    'flexSign flips the curl direction (host knob)');
}

// 24) Grip envelope opens → closes → opens per its keyframes
{
  const eng = new MotionEngine();
  eng.play(new Grip('right', { dur: 1.0, keys: [[0, 0], [0.4, 1], [0.7, 1], [1, 0]] }));
  const dt = 1 / 60; const curl = [];
  for (let i = 0; i < 60; i++) curl.push(Math.abs(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }).rightMiddleProximal[2]));
  const mid = curl[Math.floor(0.55 * 60)];      // gripping
  ok(mid > curl[2] + 0.2 && mid > curl[58] + 0.2, 'Grip closes mid-envelope and reopens by the end');
}

// 25) Pick: arm reaches grab→place AND the fingers close on the way (one motion)
{
  const grab = [REST_HAND[0] - 0.05, REST_HAND[1] + 0.06, REST_HAND[2] + 0.10];   // into the own hand
  const place = [REST_HAND[0] + 0.10, REST_HAND[1] - 0.04, REST_HAND[2] + 0.02];  // out over the river
  const eng = new MotionEngine();
  eng.play(new Pick('right', GEO, { grab, place, style: 'gentle', dur: 2.0 }));
  const dt = 1 / 60; const trace = [];
  for (let i = 0; i < 132; i++) trace.push(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }));
  let nearGrab = 1e9, nearPlace = 1e9, maxCurl = 0, endCurl = 0;
  trace.forEach((pose, i) => {
    const hand = handAt(pose);
    nearGrab = Math.min(nearGrab, D(hand, grab));
    if (i > 60) nearPlace = Math.min(nearPlace, D(hand, place));   // place is reached in the 2nd half
    const c = Math.abs(pose.rightMiddleProximal[2]);
    maxCurl = Math.max(maxCurl, c);
    endCurl = c;
  });
  ok(nearGrab < 0.06, 'Pick reaches into the own hand (grab, err=' + nearGrab.toFixed(4) + ')');
  ok(nearPlace < 0.06, 'Pick carries the hand out to the river (place, err=' + nearPlace.toFixed(4) + ')');
  ok(maxCurl > 0.5, 'Pick closes the fingers to grip the tile');
  ok(endCurl < maxCurl - 0.2, 'Pick reopens the fingers to release at the river');
}

// 26) Pick + Grip are deterministic
{
  const trace = () => {
    const eng = new MotionEngine();
    eng.play(new Pick('right', GEO, { grab: [REST_HAND[0], REST_HAND[1] + 0.05, REST_HAND[2] + 0.08], place: [REST_HAND[0] + 0.1, REST_HAND[1], REST_HAND[2]], dur: 1.6 }));
    const dt = 1 / 60; const out = [];
    for (let i = 0; i < 96; i++) out.push(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }).rightIndexProximal.slice());
    return out;
  };
  const a = trace(), b = trace(); let same = true;
  for (let i = 0; i < a.length; i++) for (let k = 0; k < 3; k++) if (a[i][k] !== b[i][k]) same = false;
  ok(same, 'Pick is deterministic');
}

// 27) orientation-space smoothing: a BIG fast reach swings the arm SMOOTHLY —
//     the per-frame angular step changes gradually (bounded jerk), no gimbal
//     jolt from independently springing three coupled Euler axes.
{
  const target = [REST_HAND[0] + 0.28, REST_HAND[1] + 0.30, REST_HAND[2] + 0.22];  // large swing
  const eng = new MotionEngine();
  eng.play(new Reach('right', ARM, target, 0.8));    // fast (0.8s)
  const dt = 1 / 60; const qs = [];
  for (let i = 0; i < 60; i++) {
    const p = eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 });
    qs.push(qFromEulerXYZ(p.rightUpperArm));
  }
  const ang = (a, b) => { let d = a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]; d = Math.min(1, Math.abs(d)); return 2 * Math.acos(d); };
  const step = []; for (let i = 1; i < qs.length; i++) step.push(ang(qs[i], qs[i - 1]));
  let maxStep = 0, maxJerk = 0;
  for (let i = 0; i < step.length; i++) { maxStep = Math.max(maxStep, step[i]); if (i) maxJerk = Math.max(maxJerk, Math.abs(step[i] - step[i - 1])); }
  ok(maxJerk < 0.02, 'reach swing is smooth (bounded orientation jerk=' + maxJerk.toFixed(4) + ')');
  ok(maxStep < 0.2, 'reach swing has no single-frame snap (maxStep=' + maxStep.toFixed(4) + ')');
}

// 28) joint limit: an elbow-angle clamp stops the hand SHORT of a straight-arm
//     target, keeping the interior elbow angle within the allowed range.
{
  const L1 = vl(ARM.pL), L2 = vl(ARM.pH);
  const elbowAngle = (upperQ, lowerQ) => {
    const elbow = fkElbow(ARM.pU, ARM.pL, upperQ);
    const hand = fkHand(ARM.pU, ARM.pL, ARM.pH, upperQ, lowerQ);
    const a = vn(sub(ARM.pU, elbow)), b = vn(sub(hand, elbow));   // elbow→shoulder, elbow→hand
    return Math.acos(Math.max(-1, Math.min(1, dot(a, b))));       // interior angle: 0=folded … π=straight
  };
  const farStraight = [ARM.pU[0], ARM.pU[1] - (L1 + L2) * 0.98, ARM.pU[2]];  // nearly straight-down reach
  const free = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, farStraight);
  const limited = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, farStraight, { elbow: [0.35, 2.4] });
  ok(elbowAngle(free.upperQ, free.lowerQ) > 2.6, 'free solve nearly straightens the elbow');
  ok(elbowAngle(limited.upperQ, limited.lowerQ) <= 2.45, 'elbow limit holds the joint below its max angle');
}

// --- v0.7: collision / constraint pass ------------------------------------

// 29) projectOut pushes a point to just outside each collider shape
{
  const plane = projectOut([0, 0.2, 0], [{ shape: 'plane', n: [0, 1, 0], o: [0, 0.5, 0] }]);
  ok(plane[1] >= 0.5 - 1e-9, 'projectOut lifts a point above a plane');
  const sph = projectOut([0.1, 0, 0], [{ shape: 'sphere', c: [0, 0, 0], r: 0.3 }], 0.02);
  ok(Math.abs(vl(sph) - 0.32) < 1e-6, 'projectOut pushes a point to sphere surface + margin');
  const cap = projectOut([0.05, 0.5, 0], [{ shape: 'capsule', a: [0, 0, 0], b: [0, 1, 0], r: 0.2 }]);
  ok(Math.abs(Math.hypot(cap[0], cap[2]) - 0.2) < 1e-6 && Math.abs(cap[1] - 0.5) < 1e-6, 'projectOut pushes a point off a capsule axis to its radius');
  const clear = [1, 1, 1];
  ok(projectOut(clear, [{ shape: 'sphere', c: [0, 0, 0], r: 0.3 }]) === clear, 'projectOut leaves an already-clear point untouched');
}

// 30) a table-plane collider keeps the hand ON/above the surface even when the
//     raw target sits below it (clamped), vs sinking through it with none.
{
  const below = [REST_HAND[0], REST_HAND[1] - 0.15, REST_HAND[2] + 0.05];
  const yPlane = REST_HAND[1] - 0.05;
  const plane = { shape: 'plane', n: [0, 1, 0], o: [0, yPlane, 0] };
  const minHandY = (colliders) => {
    const eng = new MotionEngine();
    eng.play(new Reach('right', ARM, below, 1.2, { hold: 0.3, colliders }));
    const dt = 1 / 60; let mn = 1e9;
    for (let i = 0; i < 72; i++) mn = Math.min(mn, handAt(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }))[1]);
    return mn;
  };
  ok(minHandY(null) < yPlane - 0.02, 'without a collider the hand sinks below the plane');
  ok(minHandY([plane]) > yPlane - 0.02, 'the table-plane collider keeps the hand on/above the surface');
}

// 31) post-pose constraint: a sphere ON THE PATH of a Place keeps the SPRUNG
//     hand outside it even under spring lag (the goal-clamp alone can't, because
//     the sprung hand lags its goal and cuts the corner). makeArmConstraint FK's
//     the produced pose and re-IKs out. Function-form colliders + deterministic.
{
  const start = REST_HAND;                                   // Place's arc origin = rest hand
  const target = [start[0], start[1] - 0.05, start[2] + 0.18];   // reach out-and-down
  const c = [start[0], start[1] - 0.025, start[2] + 0.09];   // sphere straddling the straight path
  const sphere = { shape: 'sphere', c, r: 0.05 };
  const swept = (useConstraint) => {
    const eng = new MotionEngine();
    if (useConstraint) eng.addConstraint(makeArmConstraint({ side: 'right', geo: GEO, colliders: () => [sphere] }));
    eng.play(new Place('right', GEO, target, { style: 'snap' }));
    const dt = 1 / 60; const out = []; let mn = 1e9;
    for (let i = 0; i < 90; i++) { const h = handAt(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 })); mn = Math.min(mn, D(h, c)); out.push(h); }
    return { mn, out };
  };
  ok(swept(false).mn < 0.05, 'without the constraint the swept hand passes through the obstacle');
  const a = swept(true), b = swept(true);
  ok(a.mn > 0.05 - 0.005, 'the constraint keeps the sprung hand outside the sphere (minDist=' + a.mn.toFixed(4) + ')');
  let same = true;
  for (let i = 0; i < a.out.length; i++) if (D(a.out[i], b.out[i]) > 1e-12) same = false;
  ok(same, 'constrained placement is deterministic (incl. function-form colliders)');
}

// --- v0.8: anticipation + follow-through ----------------------------------

// 32) swingEnv: gathers back before the swing and settles past rest after it;
//     windup:0 collapses to the plain sin-bell (back-compat).
{
  ok(swingEnv(0.06) < 0, 'swingEnv winds up opposite before the swing (anticipation)');
  ok(swingEnv(0.5) > 0.9, 'swingEnv reaches full swing at the middle');
  ok(swingEnv(0.95) < 0, 'swingEnv overshoots past rest before settling (follow-through)');
  ok(Math.abs(swingEnv(0.25, { windup: 0, follow: 0 }) - Math.sin(0.25 * Math.PI)) < 1e-9, 'windup:0/follow:0 == the plain bell');
}

// 33) the anticipation actually reaches the POSE: a fistPump dips the arm the
//     opposite way (windup) before the pump, and overshoots past rest after.
{
  const trace = run(() => new Gesture('fistPump'));   // dur 1.0 → 60 frames
  const rest = REST.rightUpperArm[2];                 // −1.2; the pump raises z
  const z = trace.map((p) => p.rightUpperArm[2]);
  let peakI = 0; for (let i = 0; i < 60; i++) if (z[i] > z[peakI]) peakI = i;
  let minBefore = 9; for (let i = 0; i < peakI; i++) minBefore = Math.min(minBefore, z[i]);
  let minAfter = 9; for (let i = peakI; i < 60; i++) minAfter = Math.min(minAfter, z[i]);
  ok(z[peakI] > -0.2, 'fistPump still reaches full extension at the peak');
  ok(minBefore < rest - 0.03, 'the arm gathers BELOW rest before the pump (anticipation in the pose)');
  ok(minAfter < rest - 0.02, 'the arm overshoots past rest after the pump (follow-through in the pose)');
}

// 34) Place anticipation: the hand gathers BACKWARD (opposite the reach) before
//     it goes out, then reaches full extension.
{
  const target = [REST_HAND[0] + 0.12, REST_HAND[1] - 0.05, REST_HAND[2] + 0.10];
  const dir = vn(sub(target, REST_HAND));                 // reach direction
  let minProj = 9, maxProj = -9;
  for (const pose of runPlace(target, { style: 'gentle' }, 1.4)) {
    const proj = dot(sub(handAt(pose), REST_HAND), dir);  // signed distance along the reach
    minProj = Math.min(minProj, proj); maxProj = Math.max(maxProj, proj);
  }
  ok(minProj < -0.003, 'Place gathers the hand backward before reaching (anticipation, minProj=' + minProj.toFixed(4) + ')');
  ok(maxProj > 0.9 * vl(sub(target, REST_HAND)), 'Place still reaches full extension');
  // anticipate:0 removes the backward gather (back-compat / opt-out)
  let minProj0 = 9;
  for (const pose of runPlace(target, { style: 'gentle', anticipate: 0 }, 1.4)) minProj0 = Math.min(minProj0, dot(sub(handAt(pose), REST_HAND), dir));
  ok(minProj0 > -0.005, 'anticipate:0 opts out of the windup');
}

// --- v0.9: shoulder cone limit + whole-arm self-collision -------------------

// 35) shoulder cone: a big lateral target swings the upper arm past its cone
//     when free, but the limit keeps it within `shoulder` radians of rest.
{
  const restA = vn(sub(fkElbow(ARM.pU, ARM.pL, RU), ARM.pU));
  const far = [ARM.pU[0] + 0.4, ARM.pU[1] + 0.2, ARM.pU[2] + 0.2];
  const coneAng = (opts) => {
    const { upperQ } = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, far, opts);
    const a = vn(sub(fkElbow(ARM.pU, ARM.pL, upperQ), ARM.pU));
    return Math.acos(Math.max(-1, Math.min(1, dot(a, restA))));
  };
  ok(coneAng({}) > 0.5, 'free solve swings the upper arm past the cone');
  ok(coneAng({ shoulder: 0.5 }) <= 0.5 + 1e-3, 'shoulder limit holds the upper arm inside its cone');
}

// 36) whole-arm self-collision: a capsule (a torso) straddling the FOREARM at
//     full reach — the hand may be clear but the forearm dips in. makeArmConstraint
//     lifts the forearm out, not just the fingertip.
{
  const target = [REST_HAND[0] + 0.1, REST_HAND[1] - 0.02, REST_HAND[2] + 0.16];
  // find the forearm (elbow→hand) at full reach from a plain Place
  let elb, hnd, best = -9;
  for (const pose of runPlace(target, { style: 'gentle' }, 1.2)) {
    const uq = qFromEulerXYZ(pose.rightUpperArm);
    const hand = handAt(pose), reach = dot(sub(hand, ARM.pU), vn(sub(target, ARM.pU)));
    if (reach > best) { best = reach; hnd = hand; elb = fkElbow(ARM.pU, ARM.pL, uq); }
  }
  const mid = [(elb[0] + hnd[0]) / 2, (elb[1] + hnd[1]) / 2, (elb[2] + hnd[2]) / 2];
  const fa = vn(sub(hnd, elb));                        // forearm axis
  let perp = vn([fa[1], -fa[0], 0]); if (vl(perp) < 1e-6) perp = [1, 0, 0];
  const capsule = { shape: 'capsule', a: [mid[0] - perp[0] * 0.2, mid[1] - perp[1] * 0.2, mid[2] - perp[2] * 0.2], b: [mid[0] + perp[0] * 0.2, mid[1] + perp[1] * 0.2, mid[2] + perp[2] * 0.2], r: 0.05 };
  const distSegToCap = (a, b) => { let mn = 9; for (let i = 0; i <= 6; i++) { const t = i / 6; const p = [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t]; mn = Math.min(mn, D(p, capClosest(p))); } return mn; };
  function capClosest(p) { const ab = sub(capsule.b, capsule.a); const tt = Math.max(0, Math.min(1, dot(sub(p, capsule.a), ab) / (dot(ab, ab) || 1))); return [capsule.a[0] + ab[0] * tt, capsule.a[1] + ab[1] * tt, capsule.a[2] + ab[2] * tt]; }
  const minClear = (useConstraint) => {
    const eng = new MotionEngine();
    if (useConstraint) eng.addConstraint(makeArmConstraint({ side: 'right', geo: GEO, colliders: [capsule] }));
    eng.play(new Place('right', GEO, target, { style: 'gentle' }));
    const dt = 1 / 60; let mn = 9;
    for (let i = 0; i < Math.ceil(1.2 * 60); i++) {
      const pose = eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 });
      const uq = qFromEulerXYZ(pose.rightUpperArm);
      mn = Math.min(mn, distSegToCap(fkElbow(ARM.pU, ARM.pL, uq), handAt(pose)));
    }
    return mn;
  };
  ok(minClear(false) < capsule.r, 'without the constraint the forearm dips into the torso capsule');
  ok(minClear(true) > capsule.r - 0.02, 'the constraint lifts the whole forearm out of the capsule');
}

// 35) headScratch is anatomical: the forearm folds on the natural flexion axis
//     (+z, toward the biceps) and NEVER hyperextends (z < 0 = 逆反り) at any
//     gain — the old -y fold read as a backward-bending elbow on real rigs.
{
  for (const gain of [1, 1.7]) {
    const eng = new MotionEngine();
    eng.play(new Gesture('headScratch'));
    const dt = 1 / 60; let minZ = 9, maxZ = -9, maxUp = -9;
    for (let i = 0; i < Math.ceil(2.3 * 60); i++) {
      const p = eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0, gain });
      minZ = Math.min(minZ, p.rightLowerArm[2]);
      maxZ = Math.max(maxZ, p.rightLowerArm[2]);
      maxUp = Math.max(maxUp, p.rightUpperArm[2]);
    }
    ok(minZ > -0.08, `headScratch never hyperextends the elbow (gain ${gain}, minZ=${minZ.toFixed(3)})`);
    ok(maxZ > 1.4, `headScratch folds the forearm toward the head (gain ${gain})`);
    ok(maxUp > REST.rightUpperArm[2] + 1.4, `headScratch raises the arm (gain ${gain})`);
  }
}

// --- v0.10: the acting library (所作) ----------------------------------------

// 36) all v0.10 gestures are registered, move, and settle back to rest
{
  const v10 = ['clap', 'gutsPose', 'banzai', 'fistToForehead', 'headShakeRue', 'ponder'];
  let allDur = true, allFn = true;
  for (const n of v10) { if (!(GESTURE_DUR[n] > 0)) allDur = false; if (new Gesture(n).done) allFn = false; }
  ok(allDur && allFn, 'all v0.10 gestures are registered');
  const sig = { clap: ['rightLowerArm', 2], gutsPose: ['rightLowerArm', 2], banzai: ['rightUpperArm', 2], fistToForehead: ['head', 0], headShakeRue: ['head', 0], ponder: ['rightLowerArm', 2] };
  let allMoved = true, allSettled = true;
  for (const n of v10) {
    const [bone, ax] = sig[n];
    const rest = (REST[bone] || [0, 0, 0])[ax];
    const eng = new MotionEngine(); eng.play(new Gesture(n));
    const frames = Math.ceil((GESTURE_DUR[n] + 1.0) * 60);
    let peak = 0, last = 0;
    for (let i = 0; i < frames; i++) { const p = eng.update(1 / 60, { t: i / 60, phase: 0, pose: {}, poseW: 0 }); peak = Math.max(peak, Math.abs(p[bone][ax] - rest)); last = Math.abs(p[bone][ax] - rest); }
    if (peak < 0.15) { allMoved = false; console.error('    ' + n + ' barely moved'); }
    if (last > 0.07) { allSettled = false; console.error('    ' + n + ' did not settle (' + last.toFixed(3) + ')'); }
  }
  ok(allMoved, 'every v0.10 gesture visibly moves its signature bone');
  ok(allSettled, 'every v0.10 gesture settles back to rest');
}

// helper: the FLEXION component of a lowerArm rotation, via swing-twist about
// the local Z hinge. The quat-space smoothing can emit an equivalent flipped
// Euler (x±π …), so raw euler[2] is NOT a reliable hinge measure — the twist is.
const flexZ = (euler) => {
  const q = qFromEulerXYZ(euler);
  let tw = 2 * Math.atan2(q[2], q[3]);          // twist about +Z
  if (tw > Math.PI) tw -= 2 * Math.PI;
  if (tw < -Math.PI) tw += 2 * Math.PI;
  return tw;
};

// 37) anatomy: the flexion-heavy set NEVER hyperextends either elbow
//     (right flexion is +z twist, left is −z; the wrong sign is 逆反り)
{
  let minR = 9, maxL = -9;
  for (const n of ['clap', 'gutsPose', 'banzai', 'fistToForehead', 'ponder']) {
    const eng = new MotionEngine(); eng.play(new Gesture(n));
    for (let i = 0; i < Math.ceil((GESTURE_DUR[n] + 0.5) * 60); i++) {
      const p = eng.update(1 / 60, { t: i / 60, phase: 0, pose: {}, poseW: 0, gain: 1.7 });
      minR = Math.min(minR, flexZ(p.rightLowerArm));
      maxL = Math.max(maxL, flexZ(p.leftLowerArm));
    }
  }
  ok(minR > -0.12, `v0.10 set never hyperextends the right elbow (minTwist=${minR.toFixed(3)})`);
  ok(maxL < 0.12, `v0.10 set never hyperextends the left elbow (maxTwist=${maxL.toFixed(3)})`);
}

// 38) clap actually beats: the forearm SWING (the meet axis, twist about Y)
//     oscillates around its hold — palms tapping apart/together
{
  const twistY = (euler) => { const q = qFromEulerXYZ(euler); let tw = 2 * Math.atan2(q[1], q[3]); if (tw > Math.PI) tw -= 2 * Math.PI; if (tw < -Math.PI) tw += 2 * Math.PI; return tw; };
  const eng = new MotionEngine(); eng.play(new Gesture('clap'));
  const z = [];
  for (let i = 0; i < Math.ceil(GESTURE_DUR.clap * 60); i++) z.push(twistY(eng.update(1 / 60, { t: i / 60, phase: 0, pose: {}, poseW: 0 }).rightLowerArm));
  let flips = 0;
  for (let i = 2; i < z.length; i++) { const d1 = z[i - 1] - z[i - 2], d2 = z[i] - z[i - 1]; if (d1 * d2 < 0 && Math.abs(d2) > 3e-4) flips++; }
  // the QuatSpring attenuates the 2Hz tap heavily — one clear press cycle
  // survives (visible softly); asserting presence, not count.
  ok(flips >= 1, `clap taps on a beat (${flips} direction changes)`);
}

// 39) headShakeRue: head pitches DOWN and yaw oscillates (やれやれ)
{
  const eng = new MotionEngine(); eng.play(new Gesture('headShakeRue'));
  let maxPitch = -9, yFlips = 0; const ys = [];
  for (let i = 0; i < Math.ceil(GESTURE_DUR.headShakeRue * 60); i++) { const p = eng.update(1 / 60, { t: i / 60, phase: 0, pose: {}, poseW: 0 }); maxPitch = Math.max(maxPitch, p.head[0]); ys.push(p.head[1]); }
  for (let i = 2; i < ys.length; i++) { const d1 = ys[i - 1] - ys[i - 2], d2 = ys[i] - ys[i - 1]; if (d1 * d2 < 0 && Math.abs(d2) > 1e-4) yFlips++; }
  ok(maxPitch > 0.18, 'headShakeRue drops the head (うつむき)');
  ok(yFlips >= 3, `headShakeRue shakes the head (${yFlips} yaw direction changes)`);
}

// 40) gutsPose/fistToForehead clench the fist; ponder uses BOTH arms
{
  const peakOf = (name, bone, ax) => { const eng = new MotionEngine(); eng.play(new Gesture(name)); let mx = 0; for (let i = 0; i < Math.ceil(GESTURE_DUR[name] * 60); i++) { const p = eng.update(1 / 60, { t: i / 60, phase: 0, pose: {}, poseW: 0 }); mx = Math.max(mx, Math.abs(p[bone][ax] - (REST[bone] || [0, 0, 0])[ax])); } return mx; };
  ok(peakOf('gutsPose', 'rightIndexProximal', 2) > 0.3, 'gutsPose clenches the right fist');
  ok(peakOf('fistToForehead', 'rightIndexProximal', 2) > 0.3, 'fistToForehead clenches the fist');
  ok(peakOf('ponder', 'rightLowerArm', 2) > 1.2 && peakOf('ponder', 'leftLowerArm', 1) > 0.8, 'ponder folds the right hand to the cheek AND the left forearm across');
}

console.log(`motion-engine: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);

function vl(a) { return Math.hypot(a[0], a[1], a[2]); }
// tiny vec helpers for the IK pole tests
function sub(a, b) { return [a[0] - b[0], a[1] - b[1], a[2] - b[2]]; }
function scl(a, s) { return [a[0] * s, a[1] * s, a[2] * s]; }
function dot(a, b) { return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]; }
function vn(a) { const l = vl(a) || 1; return [a[0] / l, a[1] / l, a[2] / l]; }
// elbow position (parent frame) from the solved upper-arm rotation
function fkElbow(pU, pL, upperQ) {
  const q = upperQ, p = pL;
  const tx = 2 * (q[1] * p[2] - q[2] * p[1]);
  const ty = 2 * (q[2] * p[0] - q[0] * p[2]);
  const tz = 2 * (q[0] * p[1] - q[1] * p[0]);
  return [
    pU[0] + p[0] + q[3] * tx + (q[1] * tz - q[2] * ty),
    pU[1] + p[1] + q[3] * ty + (q[2] * tx - q[0] * tz),
    pU[2] + p[2] + q[3] * tz + (q[0] * ty - q[1] * tx),
  ];
}
