// motion-engine unit tests — proves the engine runs headless (no three.js /
// browser), is deterministic, and produces a sane plain-data Pose.
//   node test.mjs    (or: npm test)
import {
  MotionEngine, Gesture, Spring, MANAGED, REST, GESTURE_DUR,
  Reach, Place, PLACE_STYLES, solveTwoBone, fkHand, qFromEulerXYZ, qToEulerXYZ,
  Grip, Pick, gripPose, FINGER_BONES, projectOut, makeArmConstraint, swingEnv,
} from './index.js';

const D = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);

let pass = 0, fail = 0;
const ok = (cond, msg) => { if (cond) { pass++; } else { fail++; console.error('  ✗ ' + msg); } };
const finite = (e) => e.every((v) => Number.isFinite(v));

// drive an engine for `steps` frames at 60fps, optionally with a queued action.
function run(makeAction) {
  const eng = new MotionEngine();
  if (makeAction) eng.play(makeAction());
  const dt = 1 / 60;
  const trace = [];
  for (let i = 0; i < 300; i++) {
    trace.push(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }));
  }
  return trace;
}

// 1) deterministic: identical inputs → byte-identical pose stream (no Math.random)
{
  const a = run(() => new Gesture('tsumogiri'));
  const b = run(() => new Gesture('tsumogiri'));
  let same = true;
  for (let i = 0; i < a.length; i++) {
    for (const bone of MANAGED) {
      const x = a[i][bone], y = b[i][bone];
      if (x[0] !== y[0] || x[1] !== y[1] || x[2] !== y[2]) same = false;
    }
  }
  ok(same, 'engine is deterministic across runs');
}

// 2) output is well-formed: every MANAGED bone present, all finite, every frame
{
  const trace = run();
  let wellFormed = true;
  for (const pose of trace) {
    for (const bone of MANAGED) {
      if (!pose[bone] || pose[bone].length !== 3 || !finite(pose[bone])) wellFormed = false;
    }
  }
  ok(wellFormed, 'pose has every MANAGED bone as a finite [x,y,z]');
}

// 3) idle is ALIVE (head actually drifts) but bounded (not flailing)
{
  const trace = run();
  const headY = trace.map((p) => p.head[1]);
  const moved = Math.max(...headY) - Math.min(...headY);
  ok(moved > 0.01, 'idle head drifts (alive, not frozen)');
  ok(Math.max(...headY.map(Math.abs)) < 0.3, 'idle head stays bounded');
}

// 4) a one-shot gesture peaks then SETTLES back toward rest
{
  const trace = run(() => new Gesture('fistPump'));   // dur 1.0s → done by frame 60
  const rz = trace.map((p) => p.rightUpperArm[2]);    // rest z = -1.2, fist raises it
  const peak = Math.max(...rz);
  const settled = rz[rz.length - 1];
  ok(peak > -0.2, 'fistPump raises the right arm well above rest');
  ok(Math.abs(settled - REST.rightUpperArm[2]) < 0.08, 'arm settles back to rest after the gesture');
}

// 5) spring is stable under a huge dt spike (tab refocus) — no NaN/blowup
{
  const s = new Spring(2.4, 0.9, 0, 0);
  s.update(100, 1);            // 100-second frame
  const v = s.update(1 / 60, 1);
  ok(Number.isFinite(v), 'spring survives a huge dt without NaN');
}

// 6) emotion micro-pose drives the head, scaled by weight
{
  const eng = new MotionEngine();
  const dt = 1 / 60;
  let last;
  for (let i = 0; i < 200; i++) last = eng.update(dt, { t: i * dt, phase: 0, pose: { headPitch: 0.2 }, poseW: 1 });
  ok(last.head[0] > 0.1, 'emotion headPitch is reflected in the head pose');
}

// --- Phase 2: inverse kinematics -------------------------------------------
// a self-consistent right-arm rig (values are arbitrary but FK-consistent;
// the test validates the MATH + Euler/quat conventions, not a specific VRM).
const ARM = { pU: [0.18, 1.3, 0], pL: [0, -0.26, 0], pH: [0, -0.24, 0], restU: [0, 0, -1.2], restL: [0, 0.3, 0] };
const RU = qFromEulerXYZ(ARM.restU), RL = qFromEulerXYZ(ARM.restL);
const REST_HAND = fkHand(ARM.pU, ARM.pL, ARM.pH, RU, RL);

// 7) Euler↔quat round-trip matches three.js 'XYZ' order (so bone.rotation.set works)
{
  const e = [0.3, -0.7, 1.1];
  const b = qToEulerXYZ(qFromEulerXYZ(e));
  ok(Math.max(Math.abs(b[0] - e[0]), Math.abs(b[1] - e[1]), Math.abs(b[2] - e[2])) < 1e-9, 'eulerXYZ↔quat round-trips (three.js convention)');
}

// 8) two-bone IK reaches any reachable hand position. Targets are generated by
//    FK of a perturbed pose so they are guaranteed inside the arm's reach shell;
//    the solver must land the hand back on each (IK∘FK = identity on position).
{
  let maxErr = 0;
  for (const dp of [[0.2, 0.1, -0.3], [-0.3, 0.4, 0.2], [0.1, -0.2, 0.5], [0.4, 0.1, -0.1], [-0.25, -0.3, 0.3]]) {
    const uq = qFromEulerXYZ([ARM.restU[0] + dp[0], ARM.restU[1] + dp[1], ARM.restU[2] + dp[2]]);
    const lq = qFromEulerXYZ([ARM.restL[0] + dp[2] * 0.5, ARM.restL[1] + dp[0] * 0.5, ARM.restL[2]]);
    const target = fkHand(ARM.pU, ARM.pL, ARM.pH, uq, lq);   // guaranteed reachable
    const { upperQ, lowerQ } = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, target);
    const hand = fkHand(ARM.pU, ARM.pL, ARM.pH, upperQ, lowerQ);
    maxErr = Math.max(maxErr, Math.hypot(hand[0] - target[0], hand[1] - target[1], hand[2] - target[2]));
  }
  ok(maxErr < 1e-3, 'two-bone IK reaches reachable hand positions (maxErr=' + maxErr.toFixed(6) + ')');
}

// 8b) POLE VECTOR: as the target sweeps, the elbow tracks CONSISTENTLY on the
//     pole side and moves smoothly (no shortest-arc flip). This is the anti-
//     "unnatural elbow" fix — the elbow must not jump plane between frames.
{
  const pole = [0, -1, -0.3];                          // push the elbow down-and-back
  const elbowAt = (t) => {
    const { upperQ } = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, t, { pole });
    return fkElbow(ARM.pU, ARM.pL, upperQ);
  };
  let sameSide = true, maxJump = 0, prev = null;
  for (let i = 0; i <= 20; i++) {
    const x = -0.4 + (0.8 * i) / 20;                   // sweep the hand left→right
    const t = [ARM.pU[0] + x, ARM.pU[1] - 0.35, ARM.pU[2] + 0.35];
    const elbow = elbowAt(t);
    // elbow offset from the shoulder→target line must lean toward the pole (y<0)
    const dir = vn(sub(t, ARM.pU));
    const off = sub(sub(elbow, ARM.pU), scl(dir, dot(sub(elbow, ARM.pU), dir)));
    if (dot(off, pole) <= 0) sameSide = false;
    if (prev) maxJump = Math.max(maxJump, D(elbow, prev));
    prev = elbow;
  }
  ok(sameSide, 'elbow stays on the pole side across a target sweep (no flip)');
  ok(maxJump < 0.08, 'elbow moves smoothly across the sweep (maxJump=' + maxJump.toFixed(4) + ')');
}

// 8c) flipping the pole flips which side the elbow bends toward
{
  const t = [ARM.pU[0] + 0.15, ARM.pU[1] - 0.3, ARM.pU[2] + 0.35];
  const down = fkElbow(ARM.pU, ARM.pL, solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, t, { pole: [0, -1, 0] }).upperQ);
  const up = fkElbow(ARM.pU, ARM.pL, solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, t, { pole: [0, 1, 0] }).upperQ);
  ok(down[1] < up[1] - 0.05, 'pole direction controls the elbow side (down pole → lower elbow)');
}

// 9) unreachable target clamps to near max extension (finite, no NaN)
{
  const far = [ARM.pU[0] + 3, ARM.pU[1], ARM.pU[2]];
  const { upperQ, lowerQ } = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, far);
  const hand = fkHand(ARM.pU, ARM.pL, ARM.pH, upperQ, lowerQ);
  const reach = Math.hypot(hand[0] - ARM.pU[0], hand[1] - ARM.pU[1], hand[2] - ARM.pU[2]);
  const L = vl(ARM.pL) + vl(ARM.pH);
  ok([...upperQ, ...lowerQ, ...hand].every(Number.isFinite) && reach > L * 0.9 && reach <= L, 'unreachable target clamps to ~max extension');
}

// 10) Reach action drives the hand to the target, then releases back to rest
{
  const target = [REST_HAND[0] + 0.1, REST_HAND[1] + 0.08, REST_HAND[2] + 0.05];
  const eng = new MotionEngine();
  eng.play(new Reach('right', ARM, target, 1.2, { hold: 0.4 }));
  const dt = 1 / 60; let peakErr = 1e9; let last;
  for (let i = 0; i < 72; i++) {                       // 1.2s reach
    last = eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 });
    const hand = fkHand(ARM.pU, ARM.pL, ARM.pH, qFromEulerXYZ(last.rightUpperArm), qFromEulerXYZ(last.rightLowerArm));
    peakErr = Math.min(peakErr, Math.hypot(hand[0] - target[0], hand[1] - target[1], hand[2] - target[2]));
  }
  ok(peakErr < 0.02, 'Reach brings the hand to the target at full extension (peakErr=' + peakErr.toFixed(4) + ')');
  for (let i = 0; i < 120; i++) last = eng.update(dt, { t: (72 + i) * dt, phase: 0, pose: {}, poseW: 0 });
  ok(Math.abs(last.rightUpperArm[2] - REST.rightUpperArm[2]) < 0.1, 'arm returns to rest after the reach');
}

// --- v0.2: Place action ----------------------------------------------------
const GEO = Object.assign({}, ARM, { restW: [0, 0, 0] });
const handAt = (pose) => fkHand(ARM.pU, ARM.pL, ARM.pH, qFromEulerXYZ(pose.rightUpperArm), qFromEulerXYZ(pose.rightLowerArm));
function runPlace(target, opts, secs = 2.2) {
  const eng = new MotionEngine();
  eng.play(new Place('right', GEO, target, opts));
  const dt = 1 / 60; const trace = [];
  for (let i = 0; i < Math.ceil(secs * 60); i++) trace.push(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }));
  return trace;
}

// 11) Place(gentle) lands the hand on the target (through the spring chain)
{
  const target = [REST_HAND[0] + 0.12, REST_HAND[1] - 0.05, REST_HAND[2] + 0.08];
  let peak = 1e9;
  for (const pose of runPlace(target, { style: 'gentle' })) peak = Math.min(peak, D(handAt(pose), target));
  ok(peak < 0.05, 'Place(gentle) lands the hand on the target (peakErr=' + peak.toFixed(4) + ')');
}

// 12) the hand ARCS up (lift over a downward target — not a straight drop)
{
  const target = [REST_HAND[0] + 0.12, REST_HAND[1] - 0.06, REST_HAND[2] + 0.08];
  let maxY = -1e9;
  for (const pose of runPlace(target, { style: 'gentle', arc: 0.1 }, 1.0)) maxY = Math.max(maxY, handAt(pose)[1]);
  ok(maxY > REST_HAND[1] + 0.01, 'hand lifts above the start (gravity lift arc, not a straight drop)');
}

// 13) Place drives the shoulder (roll/swing) and the wrist (aim/snap/twist)
{
  let sh = 0, wr = 0;
  for (const pose of runPlace([REST_HAND[0] + 0.12, REST_HAND[1], REST_HAND[2] + 0.08], { style: 'jam' }, 1.0)) {
    sh = Math.max(sh, Math.abs(pose.rightShoulder[0]) + Math.abs(pose.rightShoulder[1]));
    wr = Math.max(wr, Math.abs(pose.rightHand[0]) + Math.abs(pose.rightHand[1]) + Math.abs(pose.rightHand[2]));
  }
  ok(sh > 0.02, 'Place rolls the shoulder (clavicle lead)');
  ok(wr > 0.02, 'Place drives the wrist independently (aim/snap/twist)');
}

// 14) snap gives a sharper wrist flick than gentle (peak angular speed)
{
  const peakWristSpeed = (style) => {
    let prev = null, mx = 0; const dt = 1 / 60;
    for (const pose of runPlace([REST_HAND[0] + 0.1, REST_HAND[1], REST_HAND[2] + 0.06], { style })) {
      const v = pose.rightHand;
      if (prev) mx = Math.max(mx, (Math.abs(v[0] - prev[0]) + Math.abs(v[1] - prev[1]) + Math.abs(v[2] - prev[2])) / dt);
      prev = v;
    }
    return mx;
  };
  ok(peakWristSpeed('snap') > peakWristSpeed('gentle') * 1.5, 'snap = a faster wrist flick than gentle');
}

// 15) linger keeps the hand on the tile longer than snap (なかなか離さない)
{
  const target = [REST_HAND[0] + 0.12, REST_HAND[1] - 0.04, REST_HAND[2] + 0.08];
  const framesOn = (style) => runPlace(target, { style }).filter((pose) => D(handAt(pose), target) < 0.04).length;
  ok(framesOn('linger') > framesOn('snap'), 'linger dwells on the tile longer than snap');
}

// 16) Place is deterministic
{
  const run = () => runPlace([REST_HAND[0] + 0.1, REST_HAND[1], REST_HAND[2] + 0.06], { style: 'jam' }, 1.4).map((p) => p.rightHand);
  const a = run(), b = run(); let same = true;
  for (let i = 0; i < a.length; i++) for (let k = 0; k < 3; k++) if (a[i][k] !== b[i][k]) same = false;
  ok(same, 'Place is deterministic');
}

// --- v0.3: richer one-shot gestures ----------------------------------------

// 17) every new gesture is registered (has a duration) and is a known function
{
  const v03 = ['recoil', 'crossArms', 'nod', 'shrug', 'lean', 'smirkTilt', 'sigh', 'exhale'];
  let allDur = true, allFn = true;
  for (const name of v03) {
    if (!(GESTURE_DUR[name] > 0)) allDur = false;
    if (new Gesture(name).done) allFn = false;   // ctor sets done=true when the fn is missing
  }
  ok(allDur, 'all v0.3 gestures have a duration');
  ok(allFn, 'all v0.3 gestures resolve to a real function (not no-op)');
}

// 18) each new gesture actually MOVES its signature bone, then settles back
{
  // bone whose displacement from rest is the gesture's "tell"
  const sig = { recoil: 'chest', crossArms: 'rightLowerArm', nod: 'head', shrug: 'rightShoulder', lean: 'spine', smirkTilt: 'head' };
  const axis = { recoil: 0, crossArms: 1, nod: 0, shrug: 2, lean: 0, smirkTilt: 2 };
  let allMoved = true, allSettled = true;
  for (const name of Object.keys(sig)) {
    const bone = sig[name], ax = axis[name];
    const rest = (REST[bone] || [0, 0, 0])[ax];
    const trace = run(() => new Gesture(name));
    let peak = 0; for (const p of trace) peak = Math.max(peak, Math.abs(p[bone][ax] - rest));
    const settled = Math.abs(trace[trace.length - 1][bone][ax] - rest);
    if (peak < 0.12) { allMoved = false; console.error('    ' + name + ' barely moved (peak=' + peak.toFixed(3) + ')'); }
    if (settled > 0.06) { allSettled = false; console.error('    ' + name + ' did not settle (residual=' + settled.toFixed(3) + ')'); }
  }
  ok(allMoved, 'every v0.3 gesture visibly moves its signature bone');
  ok(allSettled, 'every v0.3 gesture settles back to rest when done');
}

// 19) crossArms folds BOTH forearms inward (left −Y, right +Y past rest)
{
  const trace = run(() => new Gesture('crossArms'));
  let lMin = 9, rMax = -9;
  for (const p of trace) { lMin = Math.min(lMin, p.leftLowerArm[1]); rMax = Math.max(rMax, p.rightLowerArm[1]); }
  ok(lMin < REST.leftLowerArm[1] - 0.3 && rMax > REST.rightLowerArm[1] + 0.3, 'crossArms bends both forearms across the chest');
}

// 20) the new gestures are deterministic (no Math.random)
{
  const a = run(() => new Gesture('recoil')), b = run(() => new Gesture('recoil'));
  let same = true;
  for (let i = 0; i < a.length; i++) for (const bone of MANAGED) for (let k = 0; k < 3; k++) if (a[i][bone][k] !== b[i][bone][k]) same = false;
  ok(same, 'v0.3 gestures are deterministic');
}

// 21) ctx.gain (v0.4) scales gesture amplitude — big vs reserved reactions
{
  const peakChest = (gain) => {
    const eng = new MotionEngine();
    eng.play(new Gesture('recoil'));
    const dt = 1 / 60; let mx = 0;
    for (let i = 0; i < 90; i++) {
      const ctx = { t: i * dt, phase: 0, pose: {}, poseW: 0 };
      if (gain != null) ctx.gain = gain;
      const p = eng.update(dt, ctx);
      mx = Math.max(mx, Math.abs(p.chest[0]));
    }
    return mx;
  };
  const lo = peakChest(0.5), mid = peakChest(1), hi = peakChest(2);
  ok(hi > mid * 1.4 && mid > lo * 1.4, `gain scales gesture amplitude (0.5→${lo.toFixed(3)} 1→${mid.toFixed(3)} 2→${hi.toFixed(3)})`);
  ok(Math.abs(peakChest(null) - mid) < 1e-9, 'no gain == gain 1 (back-compatible default)');
  ok(Math.abs(peakChest(99) - peakChest(2.5)) < 1e-9, 'gain is clamped (≤2.5)');
}

// --- v0.5: fingers — grip + Pick (grab a tile, carry it out, place it) -------

// 22) finger bones joined the managed rig and the engine emits them, finite
{
  const want = ['leftIndexProximal', 'rightThumbDistal', 'leftLittleIntermediate', 'rightMiddleProximal'];
  ok(want.every((b) => MANAGED.includes(b)), 'finger bones are in MANAGED');
  const last = run()[120];
  ok(want.every((b) => last[b] && finite(last[b])), 'engine emits finite finger poses');
}

// 23) gripPose: a closed grip curls the fingers; open ≈ straight; sign flips per hand
{
  const open = gripPose('right', 0);
  const closed = gripPose('right', 1);
  const openCurl = Math.abs(open.rightIndexProximal[2]);
  const closedCurl = Math.abs(closed.rightIndexProximal[2]);
  ok(openCurl < 1e-9, 'gripPose(0) leaves the finger straight');
  ok(closedCurl > 0.5, 'gripPose(1) curls the finger toward the palm');
  ok(Math.sign(gripPose('left', 1).leftIndexProximal[2]) === -Math.sign(closed.rightIndexProximal[2]),
    'left/right fingers curl with opposite Z sign');
  ok(Math.sign(gripPose('right', 1, { flexSign: -1 }).rightIndexProximal[2]) === -Math.sign(closedCurl ? closed.rightIndexProximal[2] : 1),
    'flexSign flips the curl direction (host knob)');
}

// 24) Grip envelope opens → closes → opens per its keyframes
{
  const eng = new MotionEngine();
  eng.play(new Grip('right', { dur: 1.0, keys: [[0, 0], [0.4, 1], [0.7, 1], [1, 0]] }));
  const dt = 1 / 60; const curl = [];
  for (let i = 0; i < 60; i++) curl.push(Math.abs(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }).rightMiddleProximal[2]));
  const mid = curl[Math.floor(0.55 * 60)];      // gripping
  ok(mid > curl[2] + 0.2 && mid > curl[58] + 0.2, 'Grip closes mid-envelope and reopens by the end');
}

// 25) Pick: arm reaches grab→place AND the fingers close on the way (one motion)
{
  const grab = [REST_HAND[0] - 0.05, REST_HAND[1] + 0.06, REST_HAND[2] + 0.10];   // into the own hand
  const place = [REST_HAND[0] + 0.10, REST_HAND[1] - 0.04, REST_HAND[2] + 0.02];  // out over the river
  const eng = new MotionEngine();
  eng.play(new Pick('right', GEO, { grab, place, style: 'gentle', dur: 2.0 }));
  const dt = 1 / 60; const trace = [];
  for (let i = 0; i < 132; i++) trace.push(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }));
  let nearGrab = 1e9, nearPlace = 1e9, maxCurl = 0, endCurl = 0;
  trace.forEach((pose, i) => {
    const hand = handAt(pose);
    nearGrab = Math.min(nearGrab, D(hand, grab));
    if (i > 60) nearPlace = Math.min(nearPlace, D(hand, place));   // place is reached in the 2nd half
    const c = Math.abs(pose.rightMiddleProximal[2]);
    maxCurl = Math.max(maxCurl, c);
    endCurl = c;
  });
  ok(nearGrab < 0.06, 'Pick reaches into the own hand (grab, err=' + nearGrab.toFixed(4) + ')');
  ok(nearPlace < 0.06, 'Pick carries the hand out to the river (place, err=' + nearPlace.toFixed(4) + ')');
  ok(maxCurl > 0.5, 'Pick closes the fingers to grip the tile');
  ok(endCurl < maxCurl - 0.2, 'Pick reopens the fingers to release at the river');
}

// 26) Pick + Grip are deterministic
{
  const trace = () => {
    const eng = new MotionEngine();
    eng.play(new Pick('right', GEO, { grab: [REST_HAND[0], REST_HAND[1] + 0.05, REST_HAND[2] + 0.08], place: [REST_HAND[0] + 0.1, REST_HAND[1], REST_HAND[2]], dur: 1.6 }));
    const dt = 1 / 60; const out = [];
    for (let i = 0; i < 96; i++) out.push(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }).rightIndexProximal.slice());
    return out;
  };
  const a = trace(), b = trace(); let same = true;
  for (let i = 0; i < a.length; i++) for (let k = 0; k < 3; k++) if (a[i][k] !== b[i][k]) same = false;
  ok(same, 'Pick is deterministic');
}

// 27) orientation-space smoothing: a BIG fast reach swings the arm SMOOTHLY —
//     the per-frame angular step changes gradually (bounded jerk), no gimbal
//     jolt from independently springing three coupled Euler axes.
{
  const target = [REST_HAND[0] + 0.28, REST_HAND[1] + 0.30, REST_HAND[2] + 0.22];  // large swing
  const eng = new MotionEngine();
  eng.play(new Reach('right', ARM, target, 0.8));    // fast (0.8s)
  const dt = 1 / 60; const qs = [];
  for (let i = 0; i < 60; i++) {
    const p = eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 });
    qs.push(qFromEulerXYZ(p.rightUpperArm));
  }
  const ang = (a, b) => { let d = a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]; d = Math.min(1, Math.abs(d)); return 2 * Math.acos(d); };
  const step = []; for (let i = 1; i < qs.length; i++) step.push(ang(qs[i], qs[i - 1]));
  let maxStep = 0, maxJerk = 0;
  for (let i = 0; i < step.length; i++) { maxStep = Math.max(maxStep, step[i]); if (i) maxJerk = Math.max(maxJerk, Math.abs(step[i] - step[i - 1])); }
  ok(maxJerk < 0.02, 'reach swing is smooth (bounded orientation jerk=' + maxJerk.toFixed(4) + ')');
  ok(maxStep < 0.2, 'reach swing has no single-frame snap (maxStep=' + maxStep.toFixed(4) + ')');
}

// 28) joint limit: an elbow-angle clamp stops the hand SHORT of a straight-arm
//     target, keeping the interior elbow angle within the allowed range.
{
  const L1 = vl(ARM.pL), L2 = vl(ARM.pH);
  const elbowAngle = (upperQ, lowerQ) => {
    const elbow = fkElbow(ARM.pU, ARM.pL, upperQ);
    const hand = fkHand(ARM.pU, ARM.pL, ARM.pH, upperQ, lowerQ);
    const a = vn(sub(ARM.pU, elbow)), b = vn(sub(hand, elbow));   // elbow→shoulder, elbow→hand
    return Math.acos(Math.max(-1, Math.min(1, dot(a, b))));       // interior angle: 0=folded … π=straight
  };
  const farStraight = [ARM.pU[0], ARM.pU[1] - (L1 + L2) * 0.98, ARM.pU[2]];  // nearly straight-down reach
  const free = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, farStraight);
  const limited = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, farStraight, { elbow: [0.35, 2.4] });
  ok(elbowAngle(free.upperQ, free.lowerQ) > 2.6, 'free solve nearly straightens the elbow');
  ok(elbowAngle(limited.upperQ, limited.lowerQ) <= 2.45, 'elbow limit holds the joint below its max angle');
}

// --- v0.7: collision / constraint pass ------------------------------------

// 29) projectOut pushes a point to just outside each collider shape
{
  const plane = projectOut([0, 0.2, 0], [{ shape: 'plane', n: [0, 1, 0], o: [0, 0.5, 0] }]);
  ok(plane[1] >= 0.5 - 1e-9, 'projectOut lifts a point above a plane');
  const sph = projectOut([0.1, 0, 0], [{ shape: 'sphere', c: [0, 0, 0], r: 0.3 }], 0.02);
  ok(Math.abs(vl(sph) - 0.32) < 1e-6, 'projectOut pushes a point to sphere surface + margin');
  const cap = projectOut([0.05, 0.5, 0], [{ shape: 'capsule', a: [0, 0, 0], b: [0, 1, 0], r: 0.2 }]);
  ok(Math.abs(Math.hypot(cap[0], cap[2]) - 0.2) < 1e-6 && Math.abs(cap[1] - 0.5) < 1e-6, 'projectOut pushes a point off a capsule axis to its radius');
  const clear = [1, 1, 1];
  ok(projectOut(clear, [{ shape: 'sphere', c: [0, 0, 0], r: 0.3 }]) === clear, 'projectOut leaves an already-clear point untouched');
}

// 30) a table-plane collider keeps the hand ON/above the surface even when the
//     raw target sits below it (clamped), vs sinking through it with none.
{
  const below = [REST_HAND[0], REST_HAND[1] - 0.15, REST_HAND[2] + 0.05];
  const yPlane = REST_HAND[1] - 0.05;
  const plane = { shape: 'plane', n: [0, 1, 0], o: [0, yPlane, 0] };
  const minHandY = (colliders) => {
    const eng = new MotionEngine();
    eng.play(new Reach('right', ARM, below, 1.2, { hold: 0.3, colliders }));
    const dt = 1 / 60; let mn = 1e9;
    for (let i = 0; i < 72; i++) mn = Math.min(mn, handAt(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }))[1]);
    return mn;
  };
  ok(minHandY(null) < yPlane - 0.02, 'without a collider the hand sinks below the plane');
  ok(minHandY([plane]) > yPlane - 0.02, 'the table-plane collider keeps the hand on/above the surface');
}

// 31) post-pose constraint: a sphere ON THE PATH of a Place keeps the SPRUNG
//     hand outside it even under spring lag (the goal-clamp alone can't, because
//     the sprung hand lags its goal and cuts the corner). makeArmConstraint FK's
//     the produced pose and re-IKs out. Function-form colliders + deterministic.
{
  const start = REST_HAND;                                   // Place's arc origin = rest hand
  const target = [start[0], start[1] - 0.05, start[2] + 0.18];   // reach out-and-down
  const c = [start[0], start[1] - 0.025, start[2] + 0.09];   // sphere straddling the straight path
  const sphere = { shape: 'sphere', c, r: 0.05 };
  const swept = (useConstraint) => {
    const eng = new MotionEngine();
    if (useConstraint) eng.addConstraint(makeArmConstraint({ side: 'right', geo: GEO, colliders: () => [sphere] }));
    eng.play(new Place('right', GEO, target, { style: 'snap' }));
    const dt = 1 / 60; const out = []; let mn = 1e9;
    for (let i = 0; i < 90; i++) { const h = handAt(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 })); mn = Math.min(mn, D(h, c)); out.push(h); }
    return { mn, out };
  };
  ok(swept(false).mn < 0.05, 'without the constraint the swept hand passes through the obstacle');
  const a = swept(true), b = swept(true);
  ok(a.mn > 0.05 - 0.005, 'the constraint keeps the sprung hand outside the sphere (minDist=' + a.mn.toFixed(4) + ')');
  let same = true;
  for (let i = 0; i < a.out.length; i++) if (D(a.out[i], b.out[i]) > 1e-12) same = false;
  ok(same, 'constrained placement is deterministic (incl. function-form colliders)');
}

// --- v0.8: anticipation + follow-through ----------------------------------

// 32) swingEnv: gathers back before the swing and settles past rest after it;
//     windup:0 collapses to the plain sin-bell (back-compat).
{
  ok(swingEnv(0.06) < 0, 'swingEnv winds up opposite before the swing (anticipation)');
  ok(swingEnv(0.5) > 0.9, 'swingEnv reaches full swing at the middle');
  ok(swingEnv(0.95) < 0, 'swingEnv overshoots past rest before settling (follow-through)');
  ok(Math.abs(swingEnv(0.25, { windup: 0, follow: 0 }) - Math.sin(0.25 * Math.PI)) < 1e-9, 'windup:0/follow:0 == the plain bell');
}

// 33) the anticipation actually reaches the POSE: a fistPump dips the arm the
//     opposite way (windup) before the pump, and overshoots past rest after.
{
  const trace = run(() => new Gesture('fistPump'));   // dur 1.0 → 60 frames
  const rest = REST.rightUpperArm[2];                 // −1.2; the pump raises z
  const z = trace.map((p) => p.rightUpperArm[2]);
  let peakI = 0; for (let i = 0; i < 60; i++) if (z[i] > z[peakI]) peakI = i;
  let minBefore = 9; for (let i = 0; i < peakI; i++) minBefore = Math.min(minBefore, z[i]);
  let minAfter = 9; for (let i = peakI; i < 60; i++) minAfter = Math.min(minAfter, z[i]);
  ok(z[peakI] > -0.2, 'fistPump still reaches full extension at the peak');
  ok(minBefore < rest - 0.03, 'the arm gathers BELOW rest before the pump (anticipation in the pose)');
  ok(minAfter < rest - 0.02, 'the arm overshoots past rest after the pump (follow-through in the pose)');
}

// 34) Place anticipation: the hand gathers BACKWARD (opposite the reach) before
//     it goes out, then reaches full extension.
{
  const target = [REST_HAND[0] + 0.12, REST_HAND[1] - 0.05, REST_HAND[2] + 0.10];
  const dir = vn(sub(target, REST_HAND));                 // reach direction
  let minProj = 9, maxProj = -9;
  for (const pose of runPlace(target, { style: 'gentle' }, 1.4)) {
    const proj = dot(sub(handAt(pose), REST_HAND), dir);  // signed distance along the reach
    minProj = Math.min(minProj, proj); maxProj = Math.max(maxProj, proj);
  }
  ok(minProj < -0.003, 'Place gathers the hand backward before reaching (anticipation, minProj=' + minProj.toFixed(4) + ')');
  ok(maxProj > 0.9 * vl(sub(target, REST_HAND)), 'Place still reaches full extension');
  // anticipate:0 removes the backward gather (back-compat / opt-out)
  let minProj0 = 9;
  for (const pose of runPlace(target, { style: 'gentle', anticipate: 0 }, 1.4)) minProj0 = Math.min(minProj0, dot(sub(handAt(pose), REST_HAND), dir));
  ok(minProj0 > -0.005, 'anticipate:0 opts out of the windup');
}

// --- v0.9: shoulder cone limit + whole-arm self-collision -------------------

// 35) shoulder cone: a big lateral target swings the upper arm past its cone
//     when free, but the limit keeps it within `shoulder` radians of rest.
{
  const restA = vn(sub(fkElbow(ARM.pU, ARM.pL, RU), ARM.pU));
  const far = [ARM.pU[0] + 0.4, ARM.pU[1] + 0.2, ARM.pU[2] + 0.2];
  const coneAng = (opts) => {
    const { upperQ } = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, far, opts);
    const a = vn(sub(fkElbow(ARM.pU, ARM.pL, upperQ), ARM.pU));
    return Math.acos(Math.max(-1, Math.min(1, dot(a, restA))));
  };
  ok(coneAng({}) > 0.5, 'free solve swings the upper arm past the cone');
  ok(coneAng({ shoulder: 0.5 }) <= 0.5 + 1e-3, 'shoulder limit holds the upper arm inside its cone');
}

// 36) whole-arm self-collision: a capsule (a torso) straddling the FOREARM at
//     full reach — the hand may be clear but the forearm dips in. makeArmConstraint
//     lifts the forearm out, not just the fingertip.
{
  const target = [REST_HAND[0] + 0.1, REST_HAND[1] - 0.02, REST_HAND[2] + 0.16];
  // find the forearm (elbow→hand) at full reach from a plain Place
  let elb, hnd, best = -9;
  for (const pose of runPlace(target, { style: 'gentle' }, 1.2)) {
    const uq = qFromEulerXYZ(pose.rightUpperArm);
    const hand = handAt(pose), reach = dot(sub(hand, ARM.pU), vn(sub(target, ARM.pU)));
    if (reach > best) { best = reach; hnd = hand; elb = fkElbow(ARM.pU, ARM.pL, uq); }
  }
  const mid = [(elb[0] + hnd[0]) / 2, (elb[1] + hnd[1]) / 2, (elb[2] + hnd[2]) / 2];
  const fa = vn(sub(hnd, elb));                        // forearm axis
  let perp = vn([fa[1], -fa[0], 0]); if (vl(perp) < 1e-6) perp = [1, 0, 0];
  const capsule = { shape: 'capsule', a: [mid[0] - perp[0] * 0.2, mid[1] - perp[1] * 0.2, mid[2] - perp[2] * 0.2], b: [mid[0] + perp[0] * 0.2, mid[1] + perp[1] * 0.2, mid[2] + perp[2] * 0.2], r: 0.05 };
  const distSegToCap = (a, b) => { let mn = 9; for (let i = 0; i <= 6; i++) { const t = i / 6; const p = [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t]; mn = Math.min(mn, D(p, capClosest(p))); } return mn; };
  function capClosest(p) { const ab = sub(capsule.b, capsule.a); const tt = Math.max(0, Math.min(1, dot(sub(p, capsule.a), ab) / (dot(ab, ab) || 1))); return [capsule.a[0] + ab[0] * tt, capsule.a[1] + ab[1] * tt, capsule.a[2] + ab[2] * tt]; }
  const minClear = (useConstraint) => {
    const eng = new MotionEngine();
    if (useConstraint) eng.addConstraint(makeArmConstraint({ side: 'right', geo: GEO, colliders: [capsule] }));
    eng.play(new Place('right', GEO, target, { style: 'gentle' }));
    const dt = 1 / 60; let mn = 9;
    for (let i = 0; i < Math.ceil(1.2 * 60); i++) {
      const pose = eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 });
      const uq = qFromEulerXYZ(pose.rightUpperArm);
      mn = Math.min(mn, distSegToCap(fkElbow(ARM.pU, ARM.pL, uq), handAt(pose)));
    }
    return mn;
  };
  ok(minClear(false) < capsule.r, 'without the constraint the forearm dips into the torso capsule');
  ok(minClear(true) > capsule.r - 0.02, 'the constraint lifts the whole forearm out of the capsule');
}

// 35) headScratch is anatomical: the forearm folds on the natural flexion axis
//     (+z, toward the biceps) and NEVER hyperextends (z < 0 = 逆反り) at any
//     gain — the old -y fold read as a backward-bending elbow on real rigs.
{
  for (const gain of [1, 1.7]) {
    const eng = new MotionEngine();
    eng.play(new Gesture('headScratch'));
    const dt = 1 / 60; let minZ = 9, maxZ = -9, maxUp = -9;
    for (let i = 0; i < Math.ceil(2.3 * 60); i++) {
      const p = eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0, gain });
      minZ = Math.min(minZ, p.rightLowerArm[2]);
      maxZ = Math.max(maxZ, p.rightLowerArm[2]);
      maxUp = Math.max(maxUp, p.rightUpperArm[2]);
    }
    ok(minZ > -0.08, `headScratch never hyperextends the elbow (gain ${gain}, minZ=${minZ.toFixed(3)})`);
    ok(maxZ > 1.4, `headScratch folds the forearm toward the head (gain ${gain})`);
    ok(maxUp > REST.rightUpperArm[2] + 1.4, `headScratch raises the arm (gain ${gain})`);
  }
}

// --- v0.11: ArmAct — IK-driven acting (pole-guaranteed elbows) ---------------

import { ArmAct, ARM_ACTS } from './index.js';
const GEO_R = { pU: [0.06, 0, 0], pL: [0.26, 0, 0], pH: [0.24, 0, 0], restU: [0, 0, -1.2], restL: [0, 0.3, 0], basis: { out: [1, 0, 0], up: [0, 1, 0], front: [0, 0, 1] } };
const GEO_L = { pU: [-0.06, 0, 0], pL: [-0.26, 0, 0], pH: [-0.24, 0, 0], restU: [0, 0, 1.2], restL: [0, -0.3, 0], basis: { out: [-1, 0, 0], up: [0, 1, 0], front: [0, 0, 1] } };
const GEO_BOTH = { right: GEO_R, left: GEO_L };
const handOf = (pose, side) => { const g = side === 'right' ? GEO_R : GEO_L; return fkHand(g.pU, g.pL, g.pH, qFromEulerXYZ(pose[side + 'UpperArm']), qFromEulerXYZ(pose[side + 'LowerArm'])); };
const elbowOf = (pose, side) => { const g = side === 'right' ? GEO_R : GEO_L; const q = qFromEulerXYZ(pose[side + 'UpperArm']); return [g.pU[0] + (q[3]*2*(q[1]*g.pL[2]-q[2]*g.pL[1]) + g.pL[0] + (q[1]*(2*(q[0]*g.pL[1]-q[1]*g.pL[0]))-q[2]*(2*(q[2]*g.pL[0]-q[0]*g.pL[2])))), 0, 0]; };
const runAct = (name, frames) => { const eng = new MotionEngine(); const a = new ArmAct(name, GEO_BOTH); eng.play(a); const out = []; for (let i = 0; i < frames; i++) out.push(eng.update(1 / 60, { t: i / 60, phase: 0, pose: {}, poseW: 0 })); return out; };

// 36) every arm act runs, moves, and settles back to rest
{
  let allSettled = true, allMoved = true;
  for (const n of Object.keys(ARM_ACTS)) {
    const tr = runAct(n, Math.ceil((ARM_ACTS[n].dur + 1.2) * 60));
    let peak = 0;
    for (const p of tr) peak = Math.max(peak, D(handOf(p, 'right'), handOf(tr[tr.length - 1], 'right')));
    if (peak < 0.1) { allMoved = false; console.error('    ' + n + ' barely moved'); }
    const last = tr[tr.length - 1];
    const restHand = fkHand(GEO_R.pU, GEO_R.pL, GEO_R.pH, qFromEulerXYZ(GEO_R.restU), qFromEulerXYZ(GEO_R.restL));
    if (D(handOf(last, 'right'), restHand) > 0.06) { allSettled = false; console.error('    ' + n + ' did not settle'); }
  }
  ok(allMoved, 'every arm act visibly moves the hand');
  ok(allSettled, 'every arm act settles back to rest');
}

// 37) clap: the hands MEET at the front, and BOTH elbows stay on the pole side
//     (below the shoulder→hand line — the backward-fold is structurally gone)
{
  const tr = runAct('clap', Math.ceil(ARM_ACTS.clap.dur * 60));
  let minHands = 9;
  let poleOK = true;
  for (let i = 30; i < tr.length - 20; i++) {
    const hr = handOf(tr[i], 'right'), hl = handOf(tr[i], 'left');
    minHands = Math.min(minHands, D(hr, hl));
    for (const side of ['right', 'left']) {
      const g = side === 'right' ? GEO_R : GEO_L;
      const uq = qFromEulerXYZ(tr[i][side + 'UpperArm']);
      const el = [g.pU[0], g.pU[1], g.pU[2]];
      const pl2 = [g.pL[0], g.pL[1], g.pL[2]];
      // elbow = pU + R(uq)·pL
      const tx = 2 * (uq[1] * pl2[2] - uq[2] * pl2[1]), ty = 2 * (uq[2] * pl2[0] - uq[0] * pl2[2]), tz = 2 * (uq[0] * pl2[1] - uq[1] * pl2[0]);
      const elbow = [el[0] + pl2[0] + uq[3] * tx + (uq[1] * tz - uq[2] * ty), el[1] + pl2[1] + uq[3] * ty + (uq[2] * tx - uq[0] * tz), el[2] + pl2[2] + uq[3] * tz + (uq[0] * ty - uq[1] * tx)];
      const hand = handOf(tr[i], side);
      const dir = vn(sub(hand, g.pU));
      const off = sub(sub(elbow, g.pU), scl(dir, dot(sub(elbow, g.pU), dir)));
      if (vl(off) > 0.02 && off[1] > 0.02) poleOK = false;   // elbow above the line = wrong side
    }
  }
  ok(minHands < 0.12, 'clap: hands meet at the front (minGap=' + minHands.toFixed(3) + ')');
  ok(poleOK, 'clap: both elbows stay BELOW the shoulder→hand line (pole-guaranteed, no 逆折れ)');
}

// 38) banzai: both hands rise well above the shoulders (full range via IK)
{
  const tr = runAct('banzai', Math.ceil(ARM_ACTS.banzai.dur * 60));
  let maxR = -9, maxL = -9;
  for (const p of tr) { maxR = Math.max(maxR, handOf(p, 'right')[1]); maxL = Math.max(maxL, handOf(p, 'left')[1]); }
  ok(maxR > 0.3 && maxL > 0.3, `banzai: hands thrown high (R=${maxR.toFixed(2)} L=${maxL.toFixed(2)})`);
}

// 39) gutsPose / fistToForehead clench the fist; ponder drives BOTH arms
{
  const peakCurl = (name) => { const tr = runAct(name, Math.ceil(ARM_ACTS[name].dur * 60)); let mx = 0; for (const p of tr) mx = Math.max(mx, Math.abs(p.rightIndexProximal[2])); return mx; };
  ok(peakCurl('gutsPose') > 0.4, 'gutsPose clenches the fists');
  ok(peakCurl('fistToForehead') > 0.4, 'fistToForehead clenches the fist');
  const tr = runAct('ponder', Math.ceil(ARM_ACTS.ponder.dur * 60));
  let movedL = 0;
  const restL = fkHand(GEO_L.pU, GEO_L.pL, GEO_L.pH, qFromEulerXYZ(GEO_L.restU), qFromEulerXYZ(GEO_L.restL));
  for (const p of tr) movedL = Math.max(movedL, D(handOf(p, 'left'), restL));
  ok(movedL > 0.1, 'ponder moves the left arm too (肘受け)');
}

// 40) headShakeRue (still euler — head only): pitches down + oscillates yaw
{
  const eng = new MotionEngine(); eng.play(new Gesture('headShakeRue'));
  let maxPitch = -9, yFlips = 0; const ys = [];
  for (let i = 0; i < Math.ceil(GESTURE_DUR.headShakeRue * 60); i++) { const p = eng.update(1 / 60, { t: i / 60, phase: 0, pose: {}, poseW: 0 }); maxPitch = Math.max(maxPitch, p.head[0]); ys.push(p.head[1]); }
  for (let i = 2; i < ys.length; i++) { const d1 = ys[i - 1] - ys[i - 2], d2 = ys[i] - ys[i - 1]; if (d1 * d2 < 0 && Math.abs(d2) > 1e-4) yFlips++; }
  ok(maxPitch > 0.18 && yFlips >= 3, `headShakeRue drops + shakes the head (${yFlips} flips)`);
}

// 41) arm acts are deterministic
{
  const a = runAct('gutsPose', 60).map((p) => p.rightUpperArm.join(','));
  const b2 = runAct('gutsPose', 60).map((p) => p.rightUpperArm.join(','));
  ok(a.join('|') === b2.join('|'), 'ArmAct is deterministic');
}

// --- v0.12: full-body-ification — RootAct + upstreamed ArmAct extras --------
import { RootAct, ROOT_ACTS, rhf } from './index.js';

// 42) v0.12: the 14 upstreamed extra ArmActs joined ARM_ACTS with no name
// collision against the original 5, and numerically match kamishibai's
// arm-acts-extra.js (reference re-derived from the read-only source; catches
// a transcription slip during the port). NOTE: `bones` is omitted on some
// source entries (throatHand, waveHand's *torso* term aside, etc.) — compared
// only where the reference defines it.
{
  const ORIGINAL_5 = ['clap', 'gutsPose', 'banzai', 'fistToForehead', 'ponder'];
  const EXTRA_14 = [
    'cheekHands', 'coverFace', 'throatHand', 'beckon', 'salute', 'waveHand',
    'raiseHand', 'chestHand', 'handsFolded', 'armsColdClench', 'handOnHip',
    'fightFists', 'guardFists', 'pointScreen',
  ];
  ok(EXTRA_14.every((n) => ARM_ACTS[n]), 'all 14 extra ArmActs are present in ARM_ACTS');
  ok(EXTRA_14.every((n) => !ORIGINAL_5.includes(n)), 'no name collision with the original 5 ArmActs');
  ok(Object.keys(ARM_ACTS).length === ORIGINAL_5.length + EXTRA_14.length, 'ARM_ACTS has exactly 5+14 entries');

  // reference, re-derived verbatim from kamishibai tools/vrm/arm-acts-extra.js
  // (read-only source — this is a COPY for comparison, not an import)
  const REF = {
    cheekHands: { dur: 2.6, env: { windup: 0.1, anticipate: 0.05, follow: 0.12, overshoot: 0.03 },
      bones: (e) => ({ head: [e * 0.08, 0, 0] }),
      right: (e) => ({ at: [0.10, 0.30, 0.26], pole: [1, -0.6, 0], curl: 0.25 }),
      left: (e) => ({ at: [0.10, 0.30, 0.26], pole: [1, -0.6, 0], curl: 0.25 }) },
    coverFace: { dur: 2.8, env: { windup: 0.1, anticipate: 0.08, follow: 0.12, overshoot: 0.03 },
      bones: (e) => ({ head: [e * 0.18, 0, 0], chest: [e * 0.05, 0, 0] }),
      right: (e) => ({ at: [0.02, 0.34, 0.30], pole: [1, -0.5, 0], curl: 0.2 }),
      left: (e) => ({ at: [0.02, 0.34, 0.30], pole: [1, -0.5, 0], curl: 0.2 }) },
    throatHand: { dur: 1.8, env: { windup: 0.08, anticipate: 0.05, follow: 0.12, overshoot: 0.02 },
      bones: (e) => ({ head: [e * 0.1, 0, 0] }),
      right: (e) => ({ at: [0.0, 0.14, 0.28], pole: [1, -0.6, 0], curl: 0.45 }) },
    beckon: { dur: 1.6, env: { windup: 0.08, anticipate: 0.08, follow: 0.1, overshoot: 0.04 },
      bones: (e) => ({ head: [-e * 0.05, 0, 0] }),
      right: (e, p) => ({ at: [0.18, 0.20, 0.42 - Math.max(0, Math.sin(p * Math.PI * 5)) * 0.10], pole: [1, -0.5, 0], curl: 0.3 }) },
    salute: { dur: 1.7, env: { windup: 0.1, anticipate: 0.1, follow: 0.1, overshoot: 0.04 },
      bones: (e) => ({ chest: [-e * 0.06, 0, 0], head: [-e * 0.05, 0, 0] }),
      right: (e) => ({ at: [0.13, 0.50, 0.16], pole: [1, -0.15, 0], curl: 0.15, wrist: [0, 0, -0.4] }) },
    waveHand: { dur: 2.4, env: { windup: 0.1, anticipate: 0.08, follow: 0.14, overshoot: 0.05 },
      bones: (e, p) => ({ head: [-e * 0.05, 0, e * 0.06], chest: [0, 0, e * Math.sin(p * Math.PI * 9) * 0.02] }),
      right: (e, p) => ({ at: [0.22 + Math.sin(p * Math.PI * 9) * 0.16, 0.60, 0.20], pole: [1, -0.2, 0], curl: 0.08 }),
      left: (e, p) => ({ at: [0.22 - Math.sin(p * Math.PI * 9) * 0.16, 0.60, 0.20], pole: [1, -0.2, 0], curl: 0.08 }) },
    raiseHand: { dur: 1.6, env: { windup: 0.1, anticipate: 0.1, follow: 0.12, overshoot: 0.05 },
      bones: (e) => ({ chest: [-e * 0.05, 0, 0], head: [-e * 0.08, 0, 0] }),
      right: (e) => ({ at: [0.24, 0.82, 0.15], pole: [1, -0.15, 0], curl: 0.15 }) },
    chestHand: { dur: 2.4, env: { windup: 0.1, anticipate: 0.05, follow: 0.12, overshoot: 0.02 },
      bones: (e) => ({ head: [e * 0.12, 0, 0] }),
      right: (e) => ({ at: [-0.04, 0.10, 0.24], pole: [1, -0.6, 0], curl: 0.35 }) },
    handsFolded: { dur: 3.4, env: { windup: 0.12, anticipate: 0.04, follow: 0.15, overshoot: 0.02 },
      right: (e) => ({ at: [-0.02, -0.16, 0.20], pole: [0.6, -1, 0.25], curl: 0.25 }),
      left: (e) => ({ at: [-0.02, -0.16, 0.235], pole: [0.6, -1, 0.25], curl: 0.25 }) },
    armsColdClench: { dur: 4.0, env: { windup: 0.12, anticipate: 0.05, follow: 0.15, overshoot: 0.02 },
      bones: (e) => ({ head: [e * 0.06, 0, 0] }),
      right: (e) => ({ at: [0.07, 0.06, 0.20], pole: [0.15, -1, 0.05], curl: 0.7 }),
      left: (e) => ({ at: [0.07, 0.06, 0.225], pole: [0.15, -1, 0.05], curl: 0.7 }) },
    handOnHip: { dur: 4.0, env: { windup: 0.12, anticipate: 0.06, follow: 0.15, overshoot: 0.03 },
      right: (e) => ({ at: [0.15, -0.30, 0.06], pole: [1, 0.0, 0.1], curl: 0.45 }) },
    fightFists: { dur: 3.0, env: { windup: 0.14, anticipate: 0.12, follow: 0.12, overshoot: 0.06 },
      bones: (e) => ({ chest: [-e * 0.05, 0, 0], head: [-e * 0.04, 0, 0] }),
      right: (e) => ({ at: [0.16, 0.30, 0.28], pole: [1, -0.4, 0], curl: 0.95 }),
      left: (e) => ({ at: [0.16, 0.30, 0.28], pole: [1, -0.4, 0], curl: 0.95 }) },
    guardFists: { dur: 2.6, env: { windup: 0.10, anticipate: 0.10, follow: 0.12, overshoot: 0.04 },
      bones: (e) => ({ chest: [e * 0.04, 0, 0] }),
      right: (e) => ({ at: [0.03, 0.30, 0.32], pole: [1, -0.4, 0], curl: 0.95 }),
      left: (e) => ({ at: [0.06, 0.10, 0.28], pole: [0.8, -0.7, 0.2], curl: 0.95 }) },
    pointScreen: { dur: 2.0, env: { windup: 0.12, anticipate: 0.1, follow: 0.1, overshoot: 0.05 },
      bones: (e) => ({ head: [-e * 0.1, 0, 0], chest: [-e * 0.04, 0, 0] }),
      right: (e) => ({ at: [0.12, 0.55, 0.45], pole: [1, -0.2, 0], curl: 0.7 }) },
  };
  const deepClose = (a, b) => JSON.stringify(a) === JSON.stringify(b);
  let allMatch = true;
  const SAMPLES = [0.05, 0.2, 0.4, 0.6, 0.8, 0.95];
  for (const name of EXTRA_14) {
    const got = ARM_ACTS[name], ref = REF[name];
    if (got.dur !== ref.dur || !deepClose(got.env, ref.env)) { allMatch = false; console.error(`    ${name}: dur/env mismatch`); continue; }
    for (const e of SAMPLES) {
      for (const p of SAMPLES) {
        if (ref.bones && (!got.bones || !deepClose(got.bones(e, p), ref.bones(e, p)))) { allMatch = false; console.error(`    ${name}.bones mismatch @ e=${e} p=${p}`); }
        if (ref.right && (!got.right || !deepClose(got.right(e, p), ref.right(e, p)))) { allMatch = false; console.error(`    ${name}.right mismatch @ e=${e} p=${p}`); }
        if (ref.left && (!got.left || !deepClose(got.left(e, p), ref.left(e, p)))) { allMatch = false; console.error(`    ${name}.left mismatch @ e=${e} p=${p}`); }
      }
    }
  }
  ok(allMatch, 'the 14 extra ArmActs numerically match kamishibai arm-acts-extra.js (no transcription slip)');
}

// 43) v0.12: every ROOT_ACTS entry plays to completion without error and keeps
// the whole pose (bones + root) finite throughout
{
  const runRoot = (name, frames) => {
    const eng = new MotionEngine();
    eng.play(new RootAct(name));
    const out = [];
    for (let i = 0; i < frames; i++) out.push(eng.update(1 / 60, { t: i / 60, phase: 0, pose: {}, poseW: 0 }));
    return out;
  };
  let allFinite = true;
  for (const name of Object.keys(ROOT_ACTS)) {
    const tr = runRoot(name, Math.ceil((ROOT_ACTS[name].dur + 0.5) * 60));
    for (const p of tr) {
      for (const b of MANAGED) if (!finite(p[b])) allFinite = false;
      if (!finite([p.root.y, p.root.z, p.root.tilt, p.root.lookDown])) allFinite = false;
    }
  }
  ok(allFinite, 'every ROOT_ACTS entry plays with a finite bone + root pose throughout');
  ok(Object.keys(ROOT_ACTS).length === 17, 'ROOT_ACTS has all 17 kamishibai entries');
}

// 44) RootAct pitch is distributed spine:chest:neck:head = 0.35:0.30:0.20:0.15
// (kamishibai's CMU-calibrated split), and pitch positive == forward bend in
// motion-engine's OWN convention (no BOW_SIGN baked in — see the docs note).
// Uses a large synthetic constant-pitch act (held long enough for the springs
// to settle) so the ~0.03-amplitude idle-noise layer on spine/chest/head can't
// meaningfully skew the ratio — a real act like 'bow' peaks too close to idle's
// own noise floor on 'head' to isolate the split precisely.
{
  ROOT_ACTS.__pitchTest = { dur: 3.0, f: () => ({ pitch: 12 }) };
  const eng = new MotionEngine();
  eng.play(new RootAct('__pitchTest'));
  let last;
  for (let i = 0; i < 150; i++) last = eng.update(1 / 60, { t: i / 60, phase: 0, pose: {}, poseW: 0 });
  delete ROOT_ACTS.__pitchTest;
  const v = { spine: last.spine[0], chest: last.chest[0], neck: last.neck[0], head: last.head[0] };
  ok(v.spine > 0 && v.chest > 0 && v.neck > 0 && v.head > 0, 'pitch: all 4 spine-chain bones bend POSITIVE (forward), matching motion-engine\'s own convention');
  const ratio = (a, b) => v[a] / v[b];
  ok(Math.abs(ratio('spine', 'chest') - 0.35 / 0.30) < 0.01, 'spine:chest matches the 0.35:0.30 split');
  ok(Math.abs(ratio('chest', 'neck') - 0.30 / 0.20) < 0.01, 'chest:neck matches the 0.30:0.20 split');
  ok(Math.abs(ratio('neck', 'head') - 0.20 / 0.15) < 0.01, 'neck:head matches the 0.20:0.15 split');
}

// 44b) v0.12: ROOT_ACTS numerically matches kamishibai host.html's ROOT_ACTS
// (reference re-derived from the read-only source; catches a transcription
// slip during the port — the same "移植漏れ検出" guard as the ArmAct check
// above). rhf is the shared primitive (already covered by its own shape test),
// so entries just call the SAME imported `rhf`, matching kamishibai's inline copy.
{
  const REF = {
    jump: { dur: 0.9, f: (p) => ({ y: Math.abs(Math.sin(p * Math.PI * 2)) * 0.14 }) },
    hop: { dur: 0.55, f: (p) => ({ y: Math.sin(Math.min(1, p) * Math.PI) * 0.20 }) },
    stomp: { dur: 1.3, f: (p) => ({ y: -Math.abs(Math.sin(p * Math.PI * 4)) * 0.05 }) },
    crouch: { dur: 3.2, cam: 'pull', f: (p) => { const e = rhf(p, 0.18, 0.22); return { y: -0.38 * e, pitch: 0.45 * e }; } },
    kneel: { dur: 3.2, cam: 'pull', f: (p) => { const e = rhf(p, 0.25, 0.25); return { y: -0.50 * e, pitch: 0.30 * e }; } },
    collapse: { dur: 2.8, cam: 'pull', f: (p) => { const e = rhf(p, 0.15, 0.30); return { y: -0.42 * e, z: -0.15 * e, pitch: -0.25 * e }; } },
    backstep: { dur: 0.9, f: (p) => { const e = rhf(p, 0.3, 0.3); return { z: -0.14 * e }; } },
    zukkoke: { dur: 1.1, f: (p) => { const e = rhf(p, 0.2, 0.35); return { tilt: 0.40 * e, y: -0.08 * e }; } },
    zukkokeLite: { dur: 0.9, f: (p) => { const e = rhf(p, 0.2, 0.4); return { tilt: 0.22 * e }; } },
    bow: { dur: 1.6, noLook: true, f: (p) => { const e = rhf(p, 0.40, 0.35); return { pitch: 0.26 * e }; } },
    bowDeep: { dur: 3.2, cam: 'pull', noLook: true, f: (p) => { const e = rhf(p, 0.50, 0.30); return { pitch: 1.5 * e, y: -0.05 * e, sh: 0.12 * e }; } },
    bowQuick: { dur: 0.9, noLook: true, f: (p) => { const e = rhf(p, 0.18, 0.32); return { pitch: 0.44 * e, hp: 0.1 * e }; } },
    bowInsolent: { dur: 3.2, noLook: true, pip: true, f: (p) => {
      if (p < 0.38) { const e = rhf(p / 0.38, 0.3, 0.02); return { hp: -0.16 * e, lookDown: 0.9 * e }; }
      const q = (p - 0.38) / 0.62, e = rhf(q, 0.14, 0.42);
      return { pitch: 0.22 * e, hp: 0.36 * e };
    } },
    shina: { dur: 4.2, f: (p) => { const e = rhf(p, 0.22, 0.22); return { tilt: 0.12 * e, cr: -0.17 * e, hr: 0.20 * e }; } },
    bowSorry: { dur: 3.8, cam: 'pull', noLook: true, f: (p) => { const e = rhf(p, 0.55, 0.25); return { pitch: 1.1 * e, sh: 0.3 * e, y: -0.04 * e }; } },
    doubletake: { dur: 0.8, f: (p) => ({ yaw: Math.sin(p * Math.PI * 3) * 0.30 }) },
    nodOff: { dur: 4.0, noLook: true, f: (p) => ({ pitch: Math.max(0, Math.sin(p * Math.PI * 2)) * 0.25, hp: 0.1 }) },
  };
  const SAMPLES = [0, 0.05, 0.15, 0.25, 0.38, 0.5, 0.65, 0.8, 0.95, 1];
  let allMatch = true;
  for (const name of Object.keys(REF)) {
    const got = ROOT_ACTS[name], ref = REF[name];
    if (!got) { allMatch = false; console.error(`    ${name}: missing from ROOT_ACTS`); continue; }
    if (got.dur !== ref.dur || !!got.cam !== !!ref.cam || (got.cam || null) !== (ref.cam || null)
      || !!got.noLook !== !!ref.noLook || !!got.pip !== !!ref.pip) {
      allMatch = false; console.error(`    ${name}: dur/cam/noLook/pip metadata mismatch`);
    }
    for (const p of SAMPLES) {
      if (JSON.stringify(got.f(p)) !== JSON.stringify(ref.f(p))) { allMatch = false; console.error(`    ${name}.f(${p}) mismatch`); }
    }
  }
  ok(allMatch, 'ROOT_ACTS numerically + metadata matches kamishibai host.html (no transcription slip)');
}

// 45) Pose.root carries the whole-body channels as a SEPARATE, non-bone key —
// present (all-zero) even with no RootAct queued, so an old consumer that only
// ever reads pose[boneName] (getNormalizedBoneNode-style) never even sees it
{
  const eng = new MotionEngine();
  const p = eng.update(1 / 60, { t: 0, phase: 0, pose: {}, poseW: 0 });
  ok(p.root && typeof p.root.y === 'number' && typeof p.root.z === 'number'
    && typeof p.root.tilt === 'number' && typeof p.root.lookDown === 'number',
    'pose.root exists with numeric y/z/tilt/lookDown even when idle');
  ok(p.root.y === 0 && p.root.z === 0 && p.root.tilt === 0 && p.root.lookDown === 0, 'pose.root is all-zero with no RootAct playing');
  ok(!MANAGED.includes('root'), '"root" is not a bone name — never collides with a real bone key');
}

// 46) old-Pose-only consumer simulation (#7 compat): a consumer written against
// the PRE-v0.12 bone set (no 'neck', no 'root') ignores both additions and
// still drives every bone it knows about with finite numbers, unmodified
{
  const OLD_BONES = [
    'spine', 'chest', 'head',
    'leftShoulder', 'leftUpperArm', 'leftLowerArm', 'leftHand',
    'rightShoulder', 'rightUpperArm', 'rightLowerArm', 'rightHand',
    ...FINGER_BONES,
  ];
  const eng = new MotionEngine();
  eng.play(new RootAct('bowDeep'));   // exercises root.y/root channels + trunk bend
  eng.play(new Gesture('fistPump'));
  let ok1 = true;
  for (let i = 0; i < 200; i++) {
    const pose = eng.update(1 / 60, { t: i / 60, phase: 0, pose: {}, poseW: 0 });
    // an "old" renderer: apply only bones it recognizes, via a fake getNode
    // that returns null for anything unknown (exactly like real VRM.humanoid)
    const fakeGetNode = (b) => (OLD_BONES.includes(b) ? {} : null);
    for (const b in pose) {
      const node = fakeGetNode(b);
      if (node) { if (!Array.isArray(pose[b]) || !finite(pose[b])) ok1 = false; }
      // unknown keys ('neck', 'root') are silently skipped — no throw, no NaN read
    }
  }
  ok(ok1, 'a pre-v0.12 consumer (unaware of neck/root) drives every bone it knows about unmodified');
}

console.log(`motion-engine: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);

function vl(a) { return Math.hypot(a[0], a[1], a[2]); }
// tiny vec helpers for the IK pole tests
function sub(a, b) { return [a[0] - b[0], a[1] - b[1], a[2] - b[2]]; }
function scl(a, s) { return [a[0] * s, a[1] * s, a[2] * s]; }
function dot(a, b) { return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]; }
function vn(a) { const l = vl(a) || 1; return [a[0] / l, a[1] / l, a[2] / l]; }
// elbow position (parent frame) from the solved upper-arm rotation
function fkElbow(pU, pL, upperQ) {
  const q = upperQ, p = pL;
  const tx = 2 * (q[1] * p[2] - q[2] * p[1]);
  const ty = 2 * (q[2] * p[0] - q[0] * p[2]);
  const tz = 2 * (q[0] * p[1] - q[1] * p[0]);
  return [
    pU[0] + p[0] + q[3] * tx + (q[1] * tz - q[2] * ty),
    pU[1] + p[1] + q[3] * ty + (q[2] * tx - q[0] * tz),
    pU[2] + p[2] + q[3] * tz + (q[0] * ty - q[1] * tx),
  ];
}
