// motion-engine unit tests — proves the engine runs headless (no three.js /
// browser), is deterministic, and produces a sane plain-data Pose.
//   node test.mjs    (or: npm test)
import {
  MotionEngine, Gesture, Spring, MANAGED, REST, GESTURE_DUR,
  Reach, Place, PLACE_STYLES, solveTwoBone, fkHand, qFromEulerXYZ, qToEulerXYZ,
} from './index.js';

const D = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);

let pass = 0, fail = 0;
const ok = (cond, msg) => { if (cond) { pass++; } else { fail++; console.error('  ✗ ' + msg); } };
const finite = (e) => e.every((v) => Number.isFinite(v));

// drive an engine for `steps` frames at 60fps, optionally with a queued action.
function run(makeAction) {
  const eng = new MotionEngine();
  if (makeAction) eng.play(makeAction());
  const dt = 1 / 60;
  const trace = [];
  for (let i = 0; i < 300; i++) {
    trace.push(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }));
  }
  return trace;
}

// 1) deterministic: identical inputs → byte-identical pose stream (no Math.random)
{
  const a = run(() => new Gesture('tsumogiri'));
  const b = run(() => new Gesture('tsumogiri'));
  let same = true;
  for (let i = 0; i < a.length; i++) {
    for (const bone of MANAGED) {
      const x = a[i][bone], y = b[i][bone];
      if (x[0] !== y[0] || x[1] !== y[1] || x[2] !== y[2]) same = false;
    }
  }
  ok(same, 'engine is deterministic across runs');
}

// 2) output is well-formed: every MANAGED bone present, all finite, every frame
{
  const trace = run();
  let wellFormed = true;
  for (const pose of trace) {
    for (const bone of MANAGED) {
      if (!pose[bone] || pose[bone].length !== 3 || !finite(pose[bone])) wellFormed = false;
    }
  }
  ok(wellFormed, 'pose has every MANAGED bone as a finite [x,y,z]');
}

// 3) idle is ALIVE (head actually drifts) but bounded (not flailing)
{
  const trace = run();
  const headY = trace.map((p) => p.head[1]);
  const moved = Math.max(...headY) - Math.min(...headY);
  ok(moved > 0.01, 'idle head drifts (alive, not frozen)');
  ok(Math.max(...headY.map(Math.abs)) < 0.3, 'idle head stays bounded');
}

// 4) a one-shot gesture peaks then SETTLES back toward rest
{
  const trace = run(() => new Gesture('fistPump'));   // dur 1.0s → done by frame 60
  const rz = trace.map((p) => p.rightUpperArm[2]);    // rest z = -1.2, fist raises it
  const peak = Math.max(...rz);
  const settled = rz[rz.length - 1];
  ok(peak > -0.2, 'fistPump raises the right arm well above rest');
  ok(Math.abs(settled - REST.rightUpperArm[2]) < 0.08, 'arm settles back to rest after the gesture');
}

// 5) spring is stable under a huge dt spike (tab refocus) — no NaN/blowup
{
  const s = new Spring(2.4, 0.9, 0, 0);
  s.update(100, 1);            // 100-second frame
  const v = s.update(1 / 60, 1);
  ok(Number.isFinite(v), 'spring survives a huge dt without NaN');
}

// 6) emotion micro-pose drives the head, scaled by weight
{
  const eng = new MotionEngine();
  const dt = 1 / 60;
  let last;
  for (let i = 0; i < 200; i++) last = eng.update(dt, { t: i * dt, phase: 0, pose: { headPitch: 0.2 }, poseW: 1 });
  ok(last.head[0] > 0.1, 'emotion headPitch is reflected in the head pose');
}

// --- Phase 2: inverse kinematics -------------------------------------------
// a self-consistent right-arm rig (values are arbitrary but FK-consistent;
// the test validates the MATH + Euler/quat conventions, not a specific VRM).
const ARM = { pU: [0.18, 1.3, 0], pL: [0, -0.26, 0], pH: [0, -0.24, 0], restU: [0, 0, -1.2], restL: [0, 0.3, 0] };
const RU = qFromEulerXYZ(ARM.restU), RL = qFromEulerXYZ(ARM.restL);
const REST_HAND = fkHand(ARM.pU, ARM.pL, ARM.pH, RU, RL);

// 7) Euler↔quat round-trip matches three.js 'XYZ' order (so bone.rotation.set works)
{
  const e = [0.3, -0.7, 1.1];
  const b = qToEulerXYZ(qFromEulerXYZ(e));
  ok(Math.max(Math.abs(b[0] - e[0]), Math.abs(b[1] - e[1]), Math.abs(b[2] - e[2])) < 1e-9, 'eulerXYZ↔quat round-trips (three.js convention)');
}

// 8) two-bone IK reaches any reachable hand position. Targets are generated by
//    FK of a perturbed pose so they are guaranteed inside the arm's reach shell;
//    the solver must land the hand back on each (IK∘FK = identity on position).
{
  let maxErr = 0;
  for (const dp of [[0.2, 0.1, -0.3], [-0.3, 0.4, 0.2], [0.1, -0.2, 0.5], [0.4, 0.1, -0.1], [-0.25, -0.3, 0.3]]) {
    const uq = qFromEulerXYZ([ARM.restU[0] + dp[0], ARM.restU[1] + dp[1], ARM.restU[2] + dp[2]]);
    const lq = qFromEulerXYZ([ARM.restL[0] + dp[2] * 0.5, ARM.restL[1] + dp[0] * 0.5, ARM.restL[2]]);
    const target = fkHand(ARM.pU, ARM.pL, ARM.pH, uq, lq);   // guaranteed reachable
    const { upperQ, lowerQ } = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, target);
    const hand = fkHand(ARM.pU, ARM.pL, ARM.pH, upperQ, lowerQ);
    maxErr = Math.max(maxErr, Math.hypot(hand[0] - target[0], hand[1] - target[1], hand[2] - target[2]));
  }
  ok(maxErr < 1e-3, 'two-bone IK reaches reachable hand positions (maxErr=' + maxErr.toFixed(6) + ')');
}

// 9) unreachable target clamps to near max extension (finite, no NaN)
{
  const far = [ARM.pU[0] + 3, ARM.pU[1], ARM.pU[2]];
  const { upperQ, lowerQ } = solveTwoBone(ARM.pU, ARM.pL, ARM.pH, RU, RL, far);
  const hand = fkHand(ARM.pU, ARM.pL, ARM.pH, upperQ, lowerQ);
  const reach = Math.hypot(hand[0] - ARM.pU[0], hand[1] - ARM.pU[1], hand[2] - ARM.pU[2]);
  const L = vl(ARM.pL) + vl(ARM.pH);
  ok([...upperQ, ...lowerQ, ...hand].every(Number.isFinite) && reach > L * 0.9 && reach <= L, 'unreachable target clamps to ~max extension');
}

// 10) Reach action drives the hand to the target, then releases back to rest
{
  const target = [REST_HAND[0] + 0.1, REST_HAND[1] + 0.08, REST_HAND[2] + 0.05];
  const eng = new MotionEngine();
  eng.play(new Reach('right', ARM, target, 1.2, { hold: 0.4 }));
  const dt = 1 / 60; let peakErr = 1e9; let last;
  for (let i = 0; i < 72; i++) {                       // 1.2s reach
    last = eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 });
    const hand = fkHand(ARM.pU, ARM.pL, ARM.pH, qFromEulerXYZ(last.rightUpperArm), qFromEulerXYZ(last.rightLowerArm));
    peakErr = Math.min(peakErr, Math.hypot(hand[0] - target[0], hand[1] - target[1], hand[2] - target[2]));
  }
  ok(peakErr < 0.02, 'Reach brings the hand to the target at full extension (peakErr=' + peakErr.toFixed(4) + ')');
  for (let i = 0; i < 120; i++) last = eng.update(dt, { t: (72 + i) * dt, phase: 0, pose: {}, poseW: 0 });
  ok(Math.abs(last.rightUpperArm[2] - REST.rightUpperArm[2]) < 0.1, 'arm returns to rest after the reach');
}

// --- v0.2: Place action ----------------------------------------------------
const GEO = Object.assign({}, ARM, { restW: [0, 0, 0] });
const handAt = (pose) => fkHand(ARM.pU, ARM.pL, ARM.pH, qFromEulerXYZ(pose.rightUpperArm), qFromEulerXYZ(pose.rightLowerArm));
function runPlace(target, opts, secs = 2.2) {
  const eng = new MotionEngine();
  eng.play(new Place('right', GEO, target, opts));
  const dt = 1 / 60; const trace = [];
  for (let i = 0; i < Math.ceil(secs * 60); i++) trace.push(eng.update(dt, { t: i * dt, phase: 0, pose: {}, poseW: 0 }));
  return trace;
}

// 11) Place(gentle) lands the hand on the target (through the spring chain)
{
  const target = [REST_HAND[0] + 0.12, REST_HAND[1] - 0.05, REST_HAND[2] + 0.08];
  let peak = 1e9;
  for (const pose of runPlace(target, { style: 'gentle' })) peak = Math.min(peak, D(handAt(pose), target));
  ok(peak < 0.05, 'Place(gentle) lands the hand on the target (peakErr=' + peak.toFixed(4) + ')');
}

// 12) the hand ARCS up (lift over a downward target — not a straight drop)
{
  const target = [REST_HAND[0] + 0.12, REST_HAND[1] - 0.06, REST_HAND[2] + 0.08];
  let maxY = -1e9;
  for (const pose of runPlace(target, { style: 'gentle', arc: 0.1 }, 1.0)) maxY = Math.max(maxY, handAt(pose)[1]);
  ok(maxY > REST_HAND[1] + 0.01, 'hand lifts above the start (gravity lift arc, not a straight drop)');
}

// 13) Place drives the shoulder (roll/swing) and the wrist (aim/snap/twist)
{
  let sh = 0, wr = 0;
  for (const pose of runPlace([REST_HAND[0] + 0.12, REST_HAND[1], REST_HAND[2] + 0.08], { style: 'jam' }, 1.0)) {
    sh = Math.max(sh, Math.abs(pose.rightShoulder[0]) + Math.abs(pose.rightShoulder[1]));
    wr = Math.max(wr, Math.abs(pose.rightHand[0]) + Math.abs(pose.rightHand[1]) + Math.abs(pose.rightHand[2]));
  }
  ok(sh > 0.02, 'Place rolls the shoulder (clavicle lead)');
  ok(wr > 0.02, 'Place drives the wrist independently (aim/snap/twist)');
}

// 14) snap gives a sharper wrist flick than gentle (peak angular speed)
{
  const peakWristSpeed = (style) => {
    let prev = null, mx = 0; const dt = 1 / 60;
    for (const pose of runPlace([REST_HAND[0] + 0.1, REST_HAND[1], REST_HAND[2] + 0.06], { style })) {
      const v = pose.rightHand;
      if (prev) mx = Math.max(mx, (Math.abs(v[0] - prev[0]) + Math.abs(v[1] - prev[1]) + Math.abs(v[2] - prev[2])) / dt);
      prev = v;
    }
    return mx;
  };
  ok(peakWristSpeed('snap') > peakWristSpeed('gentle') * 1.5, 'snap = a faster wrist flick than gentle');
}

// 15) linger keeps the hand on the tile longer than snap (なかなか離さない)
{
  const target = [REST_HAND[0] + 0.12, REST_HAND[1] - 0.04, REST_HAND[2] + 0.08];
  const framesOn = (style) => runPlace(target, { style }).filter((pose) => D(handAt(pose), target) < 0.04).length;
  ok(framesOn('linger') > framesOn('snap'), 'linger dwells on the tile longer than snap');
}

// 16) Place is deterministic
{
  const run = () => runPlace([REST_HAND[0] + 0.1, REST_HAND[1], REST_HAND[2] + 0.06], { style: 'jam' }, 1.4).map((p) => p.rightHand);
  const a = run(), b = run(); let same = true;
  for (let i = 0; i < a.length; i++) for (let k = 0; k < 3; k++) if (a[i][k] !== b[i][k]) same = false;
  ok(same, 'Place is deterministic');
}

// --- v0.3: richer one-shot gestures ----------------------------------------

// 17) every new gesture is registered (has a duration) and is a known function
{
  const v03 = ['recoil', 'crossArms', 'nod', 'shrug', 'lean', 'smirkTilt', 'sigh', 'exhale'];
  let allDur = true, allFn = true;
  for (const name of v03) {
    if (!(GESTURE_DUR[name] > 0)) allDur = false;
    if (new Gesture(name).done) allFn = false;   // ctor sets done=true when the fn is missing
  }
  ok(allDur, 'all v0.3 gestures have a duration');
  ok(allFn, 'all v0.3 gestures resolve to a real function (not no-op)');
}

// 18) each new gesture actually MOVES its signature bone, then settles back
{
  // bone whose displacement from rest is the gesture's "tell"
  const sig = { recoil: 'chest', crossArms: 'rightLowerArm', nod: 'head', shrug: 'rightShoulder', lean: 'spine', smirkTilt: 'head' };
  const axis = { recoil: 0, crossArms: 1, nod: 0, shrug: 2, lean: 0, smirkTilt: 2 };
  let allMoved = true, allSettled = true;
  for (const name of Object.keys(sig)) {
    const bone = sig[name], ax = axis[name];
    const rest = (REST[bone] || [0, 0, 0])[ax];
    const trace = run(() => new Gesture(name));
    let peak = 0; for (const p of trace) peak = Math.max(peak, Math.abs(p[bone][ax] - rest));
    const settled = Math.abs(trace[trace.length - 1][bone][ax] - rest);
    if (peak < 0.12) { allMoved = false; console.error('    ' + name + ' barely moved (peak=' + peak.toFixed(3) + ')'); }
    if (settled > 0.06) { allSettled = false; console.error('    ' + name + ' did not settle (residual=' + settled.toFixed(3) + ')'); }
  }
  ok(allMoved, 'every v0.3 gesture visibly moves its signature bone');
  ok(allSettled, 'every v0.3 gesture settles back to rest when done');
}

// 19) crossArms folds BOTH forearms inward (left −Y, right +Y past rest)
{
  const trace = run(() => new Gesture('crossArms'));
  let lMin = 9, rMax = -9;
  for (const p of trace) { lMin = Math.min(lMin, p.leftLowerArm[1]); rMax = Math.max(rMax, p.rightLowerArm[1]); }
  ok(lMin < REST.leftLowerArm[1] - 0.3 && rMax > REST.rightLowerArm[1] + 0.3, 'crossArms bends both forearms across the chest');
}

// 20) the new gestures are deterministic (no Math.random)
{
  const a = run(() => new Gesture('recoil')), b = run(() => new Gesture('recoil'));
  let same = true;
  for (let i = 0; i < a.length; i++) for (const bone of MANAGED) for (let k = 0; k < 3; k++) if (a[i][bone][k] !== b[i][bone][k]) same = false;
  ok(same, 'v0.3 gestures are deterministic');
}

// 21) ctx.gain (v0.4) scales gesture amplitude — big vs reserved reactions
{
  const peakChest = (gain) => {
    const eng = new MotionEngine();
    eng.play(new Gesture('recoil'));
    const dt = 1 / 60; let mx = 0;
    for (let i = 0; i < 90; i++) {
      const ctx = { t: i * dt, phase: 0, pose: {}, poseW: 0 };
      if (gain != null) ctx.gain = gain;
      const p = eng.update(dt, ctx);
      mx = Math.max(mx, Math.abs(p.chest[0]));
    }
    return mx;
  };
  const lo = peakChest(0.5), mid = peakChest(1), hi = peakChest(2);
  ok(hi > mid * 1.4 && mid > lo * 1.4, `gain scales gesture amplitude (0.5→${lo.toFixed(3)} 1→${mid.toFixed(3)} 2→${hi.toFixed(3)})`);
  ok(Math.abs(peakChest(null) - mid) < 1e-9, 'no gain == gain 1 (back-compatible default)');
  ok(Math.abs(peakChest(99) - peakChest(2.5)) < 1e-9, 'gain is clamped (≤2.5)');
}

console.log(`motion-engine: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);

function vl(a) { return Math.hypot(a[0], a[1], a[2]); }
